### ISSUE TITLE
Emoji in subject lines

### ISSUE THREAD

**Issue by utagawal** [phpList/phplist3#1000]
Refering to this report it would be nice to have the behavior by default : https://discuss.phplist.org/t/emoji-in-subject-line/8772

With version 3.6.14 there is now a Database error 1366 while doing query Incorrect string value: '\xF0\x9F\x94\xA7 e...' for column `phplist`.`phplist_messagedata`.`data` at row 1

when trying to send a campaign containing a subject with emojis "3437 🔧 et rouler de nuit 🌛"

Database collation is utf8mb4_general_ci

Used to work with phplist 3.6.12

**Comment by michield** [comment]
Yes, that's being discussed in #978
