### ISSUE TITLE
Difficulty to import emails

### ISSUE THREAD

**Issue by josephcollinsjrforpresident** [phpList/phplist3#1011]
Difficulty to import emails on phplist.  We have tried all three ways to import a email list. But it will not upload more that 795 emails. We are uploading  a total of 100k emails. 
We have tried to upload 1000 emails at a time. we have tried 500 emails at a time. we are using the latest version of phplist.

we are stuck, like a truck in the mud can someone help.

**Comment by michield** [comment]
Check your server config, maybe it cuts off the process too soon. phpList can import files that are much bigger than that. Alternatively you can use the commandline to import

**Comment by josephcollinsjrforpresident** [comment]
What part of the config  should I be looking for? and I don't know how to do a command line upload. Are there instructions?

**Comment by michield** [comment]
You need to ask your system administrator. Alternatively, use the [Docker image](https://hub.docker.com/u/phplist) instead.
