### ISSUE TITLE
Cannot create new super admins

### ISSUE THREAD

**Issue by bramley** [phpList/phplist3#1012]
This recent change  [disallow non-Superusers to manage admins](https://github.com/phpList/phplist3/commit/70e9a8b544d65ec0a84239b4db7729d86dee4cd9)
stops the creation of new super admins. The problem was raised on the support forum https://discuss.phplist.org/t/multiple-super-admins-no-longer-possible/9303

The setting of variable `$accesslevel` was removed but that is used later in the code to decide whether to display the Yes/No select list for whether the new admin is a super admin.

**Comment by michield** [comment]
This is now resolved
