### ISSUE TITLE
Unsubscribe with confirmation: why system does not to delete my email?

### ISSUE THREAD

**Issue by manuelsongokuh** [phpList/phplist3#1037]
hi
i do testing phplist 3.6.15. i did registed my email subscribed in system, this is works.

my system admin>users> there is my email, icon is green "CHECKED"

 instead unsubscribe my email is works but...message page web said:
`"You have been unsubscribed from our newsletters and you will receive a confirmation message shortly."`

in email:
```
Goodbye from our Newsletter, sorry to see you go.

You have been unsubscribed from our newsletters.

This is the last email you will receive from us. Our newsletter system, phpList,
will refuse to send you any further messages, without manual intervention by our administrator.

If there is an error in this information, you can re-subscribe:
please go to https://newsletter.yana.lol/ITA/?p=subscribe and follow the steps.

Thank you 
```

that CONFIRMATION.. mean is when email will be arrive inbox and will be confirmed unsubscribed, is it right?

so i go my system admin>users> there is my email,  the icon is "BLOCK" but 

**why system does not to delete my email?**

**Comment by michield** [comment]
Often an unsubscribe was un-intentional and if the system were to delete the profile, the history would be lost. It should be possible to revert the unsubscribe. 

You can permanently delete profiles on the "Reconcile subscribers" page.
