### ISSUE TITLE
Reorganisation of the resources site breaks Find plugins link

### ISSUE THREAD

**Issue by bramley** [phpList/phplist3#1043]
The resources site https://resources.phplist.com appears to have been reorganised, changing the format of URLs.

Now the page that lists available plugins has the URL https://resources.phplist.com/doku.php?id=plugins:start but the Find plugins link on the Plugins page uses http://resources.phplist.com/plugins/

Any other references to a plugin's documentation page are also going to fail, including the Documentation Page link for each plugin on the Plugins page.

Also, I have tended to link to the documentation page in the GitHub README file.
![image](https://github.com/phpList/phplist3/assets/3147688/f2c68d99-8e75-44da-8e46-767f1599bf70)

It should be possible to define a mod_rewrite rule to change old format URLs to the new format.

**Comment by bramley** [comment]
Possibly URL rewriting needs to be enabled in dokuwiki https://www.dokuwiki.org/rewrite
Option 1 web server seems to match how URLs were handled previously.

**Comment by maartee** [comment]
@bramley Thanks for reporting this. Some settings were missing from the old config file. Please check now.

**Comment by bramley** [comment]
Thanks, the links are now working again.
Can you see whether the dokuwiki Wrap plugin has been disabled? This syntax used to display an information box but now is just displayed literally
```
<WRAP center round tip 60%>
xxxx 
</WRAP>

**Comment by maartee** [comment]
Good catch! Corrected.

**Comment by maartee** [comment]
FYI: the upgrade of original obsolete version of dokuwiki required several changes of the underlying system, and also migrating data to fresh dokuwiki installation. That was the source of the issues above.

**Comment by bramley** [comment]
Thanks, the wrap is working as expected now.

One other question about on navigation. The breadcrumb when viewing a plugin page goes to `/plugin/start `which shows an attempt to redirect to `/plugins/start` which shows a list of all the plugins.
![image](https://github.com/phpList/phplist3/assets/3147688/1c49ad2b-0e08-4ad3-8733-27f3bf6d18cf)

I think that this worked previously. Perhaps the Page Redirect plugin needs to be enabled.

**Comment by bramley** [comment]
This all looks ok now. Thanks.
