### ISSUE TITLE
Update demo

### ISSUE THREAD

**Issue by fulldecent** [phpList/phplist3#1045]
The demo has an old version which is insecure.

Please install the lastest version on the demo server. Or better, use continuous integration so that new commits to this repo automatically update the demo server.

![Screenshot 2024-07-09 at 10 56 43](https://github.com/phpList/phplist3/assets/382183/0e818d72-c925-443f-b645-7a0bbedb2a47)

**Comment by michield** [comment]
The demo is 3.6.15 which is the latest, but it looks like the CKeditor that is included needs updating instead.

**Comment by michield** [comment]
This seems resolved now
