### ISSUE TITLE
Is contribution under AGPL license possible?

### ISSUE THREAD

**Issue by hakre** [phpList/phplist3#12]
If I would like to make a contribution, and the contribution is licensed under AGPL (like PHPLiist itself, perhaps even AGPL 3 or later, not 3 only), would the contribution be possible?

I ask because I'm not sure if the CLA you have would allow this.

If you answer, please do a full quote of my question in your answer.

**Comment by michield** [comment]
If you are the person who made the contribution, then you can decide what to do with it. I'm not sure how the contribution would be AGPL licensed if it is not your code. If it was made by someone else, you need to ask them to sign the CLA. If the contribution is yours, and you sign the CLA, then that's all no problem at all.

**Comment by hakre** [comment]
I meant explicitly with no CLA but validly under AGPL and compatible with the license of phplist itself. Like forking phplist under AGPL, doing changes and then contributing back to phpList.

Just no further rights as those governed by the AGPL license. Like you license the software to everybody else as well.

**Comment by michield** [comment]
At this stage I can't accept contributions to the core of phpList without the CLA. The CLA actually explicitly states that the code will always remain AGPL, so that should be fine.

**Comment by hakre** [comment]
That part of the CLA does not have the word *"only"* in it. My question is about whether you're using the CLA because you have intend to re-license the contribution under different licensing terms as well.

**Comment by michield** [comment]
At this moment in time I do not intend to. But learning from other projects like ownCloud, I do not want to close that door either. Also, apart from re-licensing, having a single entity with the core code rights allows for better (more efficient) protection in court, in case of violations. That is the reason that the FSF is [requesting a CLA as well] (https://www.gnu.org/licenses/why-assign.html)

So, that's two reasons. Possible expansion into new revenue streams that make the project more economically viable and able to survive (re-licensing) and ensuring that the AGPL license most effectively protected (one sole copyright holder).

If this is important to you, then it may be best to write a plugin instead. The CLA only applies to the core code. Plugins have their own license.

**Comment by michield** [comment]
But of course, send me an absolutely amazing PR, that I will want to merge without any doubts, because it brings me coffee in the morning (or something similar), and tell me you can't sign the CLA and I may change my mind. Eventually, this is a meritocracy.

**Comment by hakre** [comment]
Thanks for talking openly. And yeah, cheers. Coffee in the morning is good.
