### ISSUE TITLE
Provide a HTTPS version of powered.phplist.com and use that for images

### ISSUE THREAD

**Issue by oliverklee** [phpList/phplist3#133]
On the start page of my PHPList page, there is an image:

http://powered.phplist.com/images/3.0.5/power-phplist.png

However, as my site is HTTPS, having this HTTP-served image results in mixed-content warnings. There should either be a HTTPS version of the page/image, and the image src should use that, or the image should be served locally, not from the powered.phplist.com server.

Mixed-content warnings result in the page not being marked as secure by (at least) Chrome: https://arstechnica.com/information-technology/2015/10/chrome-finally-kills-off-the-http-https-mixed-content-warning/

This is with PHPList 3.0.5.

**Comment by michield** [comment]
Yes, good point. The HTTPS one is here https://d3u7tsw7cvar0t.cloudfront.net/images/3.0.5/power-phplist.png

**Comment by michield** [comment]
Put this in your config file: define('PHPLIST_POWEREDBY_URLROOT','https://d3u7tsw7cvar0t.cloudfront.net/images');
