### ISSUE TITLE
Drop support for PHP 5.3

### ISSUE THREAD

**Issue by oliverklee** [phpList/phplist3#137]
This is a "small version" of #136.

**Comment by michield** [comment]
would be nice to change it to an "Allow failure" instead of just zapping the version.

**Comment by oliverklee** [comment]
Why? Either it officially supports 5.3 (and then it should work, and the maintainers need to put work into keeping it working with 5.3), or 5.3 is not supported anymore, and then the tests are not needed (and also misleading). Or am I misunderstanding you?

**Comment by oliverklee** [comment]
(The point of dropping support is to reduce the needed maintenance work, and to allow for cleaner code.)
