### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by oliverklee** [phpList/phplist3#140]
The LICENSE file with the GPL is currently missing.

**Comment by michield** [comment]
Yes, how odd. Don't know where it had gone, but back now. https://github.com/phpList/phplist3/commit/c13b941c37c8dedf8494be6db883b3d44d571127

**Comment by oliverklee** [comment]
@michield Thanks! By the way, if you include something like "Fixes #140" in the body of the commit message, GitHub will auto-close the issue once the commit is merged. :-)
