### ISSUE TITLE
help return 500 error

### ISSUE THREAD

**Issue by enboig** [phpList/phplist3#147]
When entering help AJAX return a 500 error
url is example.com/lists/admin/help/?topic=message&ajaxed=true&page=pageaction&action=

I just upgraded from previous version, I don't know if this error existed before. I checked for error logs but none found.

Any hint?
Thanks

**Comment by michield** [comment]
we've had quite a few issues with version 3.3.0, so we have pulled it and will release a new version soon.

See also https://mantis.phplist.org/view.php?id=18515

**Comment by enboig** [comment]
How to downgrade? just uploading the php files?

**Comment by michield** [comment]
yes, that should work. Preferably you have the previous DB as well.
