### ISSUE TITLE
Exclude list feature is broken.

### ISSUE THREAD

**Issue by badfiles** [phpList/phplist3#171]
It is unable to choose a list to exclude. I use latest git master.
![screenshot from 2017-04-28 21-00-19](https://cloud.githubusercontent.com/assets/1597304/25541046/e8d80ec0-2c55-11e7-82c0-72d508646ba7.png)

**Comment by bramley** [comment]
I think it is the same as, or related to, the problem reported here https://mantis.phplist.org/view.php?id=18240
You can probably workaround the problem by defining a list category and assigning one list to that.

**Comment by badfiles** [comment]
Thanks for the workaround!
