### ISSUE TITLE
Installing on PHP7.1 seems to fail (badly)

### ISSUE THREAD

**Issue by ywarnier** [phpList/phplist3#182]
Hi,
I'm trying to run the latest git version from the master branch and the packaged version available for download on the site with Nginx and PHP-FPM 7.1.

The /admin/index.php page loads correctly, then I click on the "Initialise Database" link and I get sent to /admin/?page=initialise&firstinstall=1&tk=623eb2151a1586d89cd12484397a490e, where I get this:
```
Database error 1146 while doing query Table 'phplist.phplist_subscribepage' doesn't exist
Database error 1146 while doing query Table 'phplist.phplist_subscribepage' doesn't exist
Database error 1146 while doing query Table 'phplist.phplist_subscribepage' doesn't exist
Unsubscribe from our Newsletters
```
There's nothing in the error log.

I've tried to debug a little, but honestly I'm a bit lost in your code.

Why would phplist ask for phplist_subscribepage to exist if it is not installed yet? Any quick solution to this, or should I debug more?

**Comment by michield** [comment]
That looks more like you loaded the /lists/ page instead of /lists/admin/

Also, the error indicates a DB issue, not PHP7.1 related.
phpList seems to work fine on PHP7.1 according to Travis. https://travis-ci.org/phpList/phplist3/builds
