### ISSUE TITLE
Only HTML with no formatting appears after install

### ISSUE THREAD

**Issue by jvence** [phpList/phplist3#19]
I've followed the instructions to install the latest version (checked out using svn)- I successfully installed and logged into the web however there seems to be no CSS formatting whatsoever on the webapp and I just see pure HTML. Not sure if I need to define a theme or something.

**Comment by michield** [comment]
as you closed it, I presume you found out what to do?

https://resources.phplist.com/develop/infrastructure

**Comment by jvence** [comment]
Yes I did figure it out after I looked at the github dir structure. Thanks
