### ISSUE TITLE
Wrong type of "processed" counter in MySQL database structure.

### ISSUE THREAD

**Issue by alekw** [phpList/phplist3#192]
In table 'phplist_message', there is a 'processed' field, which is UNSIGNED MEDIUMINT(8).
This limits the number of recipients to 16777215 (see EDIT below), however this is not really a problem.

The thing is that other fields regarding number of processed recipients use INT: astext, ashtml, viewed, bounced etc. Their values should never exceed the 'processed' field, so this is mistake for sure.

The type of field comes most likely from https://github.com/phpList/phplist3/blob/master/public_html/lists/admin/structure.php
`'processed'     => array('mediumint unsigned default 0', 'Number Processed'),
        'astext'        => array('integer default 0', 'Sent as text'),
        'ashtml'        => array('integer default 0', 'Sent as HTML'),
        'astextandhtml' => array('integer default 0', 'Sent as Text and HTML'), // obsolete
        'aspdf'         => array('integer default 0', 'Sent as PDF'),
        'astextandpdf'  => array('integer default 0', 'Sent as Text and PDF'),
        'viewed'        => array('integer default 0', 'Was the message viewed'),`

Screenshot from phpmyadmin:
![phplist](https://user-images.githubusercontent.com/2614328/29027166-bee03a10-7b7f-11e7-8df8-dbc332a88f2f.PNG)

EDIT: actually, the 'processed' field is increased during each iteration on any recipient. When using domain throttling or there is any other reason to fail, one mail address will be processed many times. Therefore the issue is even more valid, since the processed number can be many times larger than number of sent messages.

**Comment by samtuke** [comment]
@alekw Looks like a great catch, thanks!

**Comment by alekw** [comment]
@samtuke You're welcome. I fixed it in my installation by changing to INT, but I will not write PR for it, as it may affects upgrades and so on. Better to leave it to somebody more familiar with the code.

**Comment by samtuke** [comment]
Yes the upgrade process would need careful testing. Others will add their comments here in due course

**Comment by oliverklee** [comment]
We will also need the same change for phpList 4 so the DB schema (schemata?) stay in sync.

**Comment by michield** [comment]
the processed field is actually not a valid or useful counter. It will keep track of how many times a message is being processed. Not sent. If sending fails and it tries again later, that's two in processed, even though nothing has been sent. It's more an "activity indicator" than an actual counter.

**Comment by alekw** [comment]
@michield then maybe we can do modulo?
`$processed %= 16777215;` or something like that?

**Comment by michield** [comment]
why would you want to do that?

**Comment by alekw** [comment]
Well, I found this issue using command line processqueue. My subscriber list was way to small to cause range overflow, but it happened due to 'agressive' domain throttling.
I realized that this value has completely no meaning for whole process: changing it manually didn't cause any problem. As you said, it's just indicator.
IMHO, modulo operations will remove the issue for any number of processing the message.

**Comment by bramley** [comment]
The problem that @alekw is seeing is possibly due to the sql mode. When strict mode is enabled then trying to update the value past its maximum causes an error. When strict mode is not enabled then the field remains at its maximum value.

![image](https://user-images.githubusercontent.com/3147688/29092712-32e67d34-7c7f-11e7-81b6-fa49ccdab15c.png)

**Comment by alekw** [comment]
@bramley Exactly that is happening.

**Comment by michield** [comment]
Ah, interesting. In a way changing it to INT won't solve the problem, only postpone it. But it'll allow the value to get much bigger, I would vote for that. It is probably the least likely way to change it without causing issues. I'll fix that.

**Comment by samtuke** [comment]
@alekw Thanks for the clarifications

**Comment by michield** [comment]
https://github.com/phpList/phplist3/commit/28feeb7aa502e9a902fea3fdb32eb4a158105140
