### ISSUE TITLE
Uniqid format

### ISSUE THREAD

**Issue by jd440** [phpList/phplist3#198]
As some other I got trouble on upgrading to 3.3.1 with statistic view, with corrupted uniqid.

And I surprise that uniqid is in varchar(255) shouldn't be better to change to varchar(32)

**Comment by michield** [comment]
Sorry, it's not clear what your issue is and how to resolve it.

**Comment by jd440** [comment]
sorry about that.
Is not a specific issue. 

As uniqid must alway get a 32 length I was just surprise that uniqid is in VARCHAR(255) and not  varchar(32)

**Comment by michield** [comment]
Ah, sure. 255 gives it more flexibility to expand on the Uniqid without needing to change the DB.
