### ISSUE TITLE
Rework the Update translations page

### ISSUE THREAD

**Issue by bramley** [phpList/phplist3#218]
Currently the Update translations page presents too much information because it lists all languages, not just those whose translations have been installed. Further, only one language, the current one, can be updated and that link can be hard to see within the overall list.

I have a few suggestions

- show only those languages that have been installed
- replace the two similar labeled date fields (last updated and last modified) with a message indicating whether new translations are available
- use a Webbler listing so that the information structure is clearer
- allow any installed language to be updated, not just the currently selected language

![image](https://user-images.githubusercontent.com/3147688/32861334-482c8768-ca4c-11e7-9ee2-e8c3af3bded9.png)

**Comment by samtuke** [comment]
Looks great to me +1

**Comment by bramley** [comment]
Looking at the commit history of updatetranslations. php, it used to allow any language to be updated but that was changed to allow only the current admin language in this commit from 2013 
https://github.com/phpList/phplist3/commit/72b27ffce99b65abc48ccb50d6bc7d4a599512cc#diff-e2b5ad1b5fd76dcbe624dfc819d06fc7

Do you think that should still be the case? My proposal is to allow any of the installed languages (which will usually be one or two I guess) to be updated.

**Comment by michield** [comment]
Well, I did that at the time to avoid people updating languages they don't need, to avoid DDOSing the translation server. But your proposal will take care of that, if people choose which languages to "install" so I think it'll be fine.

**Comment by bramley** [comment]
Now addressed by PR 219
