### ISSUE TITLE
Question: How to do transaction messages in HTML instead plainText

### ISSUE THREAD

**Issue by ruslanguns** [phpList/phplist3#223]
Sorry if I am sending this question over there instead posting an issue.
Is it there any way to send transaction emails such as "Opt-In Confirmation email", "Subscription Confirmation email" and "Unsubscription confirmation email" to be able to send them in  HTML instead PlainText?

**Comment by ruslanguns** [comment]
oh by the way, I have put html tags in the messages boxes 
(This sample is in Spanish, however you get the point)
![imagen](https://user-images.githubusercontent.com/19806968/33498771-402c0ed2-d698-11e7-8259-43bc6b9519f8.png)

Looking forward in hearing back from you soon. Thanks very much in advance!

**Comment by michield** [comment]
This is more a question for the [Forums](https://discuss.phplist.org/)

When you set the System Template in the template section it will be used to wrap around the transaction messages.

**Comment by ruslanguns** [comment]
Thank you very much! I already figured it out. Just for those who want to have the details I am writing them out in the following link:

https://discuss.phplist.org/t/transacction-phplist-emails-make-them-html-instead-plain-text/3433
