### ISSUE TITLE
Subscribe page text attribute value is corrupted

### ISSUE THREAD

**Issue by bramley** [phpList/phplist3#264]
The function removeXss() in admin/inc/magic_quotes.php always htmlspecialchars() $_POST, $_GET etc for public pages
```
function removeXss($string)
{
    if (is_array($string)) {
        $return = array();
        foreach ($string as $key => $val) {
            $return[removeXss($key)] = removeXss($val);
        }
        return $return;
    }
    //$string = preg_replace('/<script/im','&lt;script',$string);
    $string = htmlspecialchars($string);
    return $string;
}
```
This results in text values, such as a company attribute, that include an & character being corrupted.
So entering `M&S` gets stored as `M&amp;S` in the database. Then is displayed as `M&amp;S` on the preferences page and if submitted is then stored as `M&amp;amp;S` in the database.

I'm not knowledgeable about how to avoid XSS but cannot believe that htmspecialchars() every parameter is necessary.

**Comment by bramley** [comment]
Removing the call to htmlspecialchars() doesn't appear to have any bad effect.
If I enter some html in a text field on the subscribe page
![image](https://user-images.githubusercontent.com/3147688/37467964-8f08c94c-2859-11e8-885c-47c479f1a21d.png)

then on the preferences page it is shown literally, because the value is html encoded prior to display
![image](https://user-images.githubusercontent.com/3147688/37468035-bf25efe2-2859-11e8-9050-43c06007a8d0.png)

**Comment by michield** [comment]
Yes, I agree, it's a bit of a sledgehammer. I'll try to find some time to investigate

**Comment by michield** [comment]
Is it only the & that is the issue, or other characters as well? We could just put &amp; back into & and stick with that.
