### ISSUE TITLE
Coding Style conventions

### ISSUE THREAD

**Issue by Soullivaneuh** [phpList/phplist3#29]
Do you follow some Coding Style conventions?

I would recommend to follow at least PSR-1/2 and maybe [Symfony](http://symfony.com/doc/current/contributing/code/standards.html) conventions.

I can propose some automatic tools to help with it.

Tell me if you are interested. :+1:

**Comment by michield** [comment]
Hmm, yes. That has always been a "would be nice" kind of thing. There used to be some style, but it's in general all over the place.

I'm interested in your tools.

**Comment by Soullivaneuh** [comment]
Okay, shall I propose them on both v3 and v4?

**Comment by michield** [comment]
You mean as a PR? Well, then only v4. On v3, I'd prefer you give me the tools, and I can check myself. Also phpStorm gave me a license, and I think they have it all built in as well. Haven't checked that yet.

**Comment by Soullivaneuh** [comment]
Wells, those tools required some configurations files and subscriptions of your repositories... would be faster with PR proposition.

**Comment by michield** [comment]
Ah, ok, sure, but a full PR on the code after using the tools will be a massive change. That may not be sensible at this stage. I'd prefer to handle that myself.
