### ISSUE TITLE
Ajax subscribe 'htmlemail' entry is hardcoded.

### ISSUE THREAD

**Issue by kuldeepdhaka** [phpList/phplist3#34]
https://github.com/phpList/phplist3/blob/master/public_html/lists/index.php#L265

**Comment by michield** [comment]
yes, doesn't everyone want it to be html nowadays?

**Comment by kuldeepdhaka** [comment]
@michield if everyone wanted html, why would **i** be querying.

**Comment by michield** [comment]
sure. Feel free to post a PR.
