### ISSUE TITLE
Use of incorrect column name of message table

### ISSUE THREAD

**Issue by bramley** [phpList/phplist3#346]
This pull request https://github.com/phpList/phplist3/pull/298 has an error 

        Sql_Query(sprintf('update %s set viewed = 0 where messageid = %d', $GLOBALS['tables']['message'], $messageid));

It should be referring to the id column of the message table.

**Comment by xh3n1** [comment]
thank you @bramley for reporting it, I will fix it.

**Comment by michield** [comment]
Thanks for spotting that @bramley
