### ISSUE TITLE
How is runcommand intended to be used?

### ISSUE THREAD

**Issue by bramley** [phpList/phplist3#353]
@michield There is a runcommand page, file admin/runcommand.php, that appears to restricted to run only from the command line. It refers to $_GET though, in particular $_GET['command']. How is that set?

**Comment by bramley** [comment]
I found that including `command=xxx` in the command but **before** the -p and -c parameters works, `$_GET['command']` is then populated.
Is that the intended way?

**Comment by michield** [comment]
Yes, that's intended.

**Comment by michield** [comment]
although, I can't remember that it needed to be before -c and -p

**Comment by bramley** [comment]
If it appears after -p and -c then it gets included in the last parameter

`
 php /home/duncan/www/lists/admin/index.php  -c /home/duncan/Development/PHP/phplist/config.php -p runcommand command=xxx
`


`Error: runcommand command=xxx does not process commandline`

**Comment by michield** [comment]
ah, yes, I remember that.
