### ISSUE TITLE
Client denied by server configuration for fckeditor connector.php

### ISSUE THREAD

**Issue by soullivaneuh** [phpList/phplist3#360]
### Short problem description
A plugin URL is going 403 and ~~I can't found why~~. I "solve" the issue by adding `connector.php` on this line: https://github.com/phpList/phplist3/blob/b9c5c46858fcfe1bf75e60b81b8d59363c5d2266/public_html/lists/admin/plugins/.htaccess#L13

### Steps to reproduce

From the editor, I go to the image server browsing, calling this url:

```
https://mailing.site.org/lists/admin/plugins/fckphplist/fckeditor/editor/filemanager/connectors/php/connector.php?Command=GetFoldersAndFiles&Type=File&CurrentFolder=%2F&uuid=1530137988035
```

### Expected behaviour
The URL should be accessible.

### Actual behaviour

```
[Thu Jun 28 00:45:41.966389 2018] [authz_core:debug] [pid 13187] mod_authz_core.c(809): [client 90.110.6.214:43194] AH01626: authorization result of Require all denied: denied
[Thu Jun 28 00:45:41.966482 2018] [authz_core:debug] [pid 13187] mod_authz_core.c(809): [client 90.110.6.214:43194] AH01626: authorization result of <RequireAny>: denied
[Thu Jun 28 00:45:41.966568 2018] [authz_core:error] [pid 13187] [client 90.110.6.214:43194] AH01630: client denied by server configuration: /var/www/site.org/mailing/current/web/lists/admin/plugins/fckphplist/fckeditor/editor/filemanager/connectors/php/connector.php
```

If there are any error messages, please include those as well.

#### Package version

3.3.1

#### PHP and Composer version

```
PHP 7.2.5-0ubuntu0.18.04.1 (cli) (built: May  9 2018 17:21:02) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.5-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies
```

```
Composer version 1.6.3 2018-01-31 16:28:17
```

#### Apache (2.4) configuration

```
<VirtualHost *:443>
    ServerName mailing.site.org
    DocumentRoot /var/www/site.org/mailing/current/web

    <Directory "/var/www/site.org/mailing/current/web">
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/mailing.site-error.log

    # Possible values include: debug, info, notice, warn, error, crit,
    # alert, emerg.
    LogLevel debug

    CustomLog ${APACHE_LOG_DIR}/mailing.site-access.log combined

    Include /etc/apache2/sites-ssl/site-org.ssl.conf
    Include /etc/apache2/letsencrypt.conf
</VirtualHost>
```

**Comment by bramley** [comment]
@Soullivaneuh Is this the plugin that was included with phplist 3.3.1 with no changes, or something else? From your description of the URL being denied, the path does not actually exist in the plugin

`plugins/fckphplist/fckeditor/editor/filemanager/connectors/php/`

**Comment by soullivaneuh** [comment]
> Is this the plugin that was included with phplist 3.3.1 with no changes, or something else?

Provided by phplist itself for sure. I didn't setup any custom plugin/library on this project.

**Comment by bramley** [comment]
@soullivaneuh  As I previously mentioned, the path you showed does not exist. The correct path  is

plugins/fckphplist/fckeditor/editor/filemanager/connectors/**phplist**/

But the fckeditor is now outdated and you should use ckeditor through the ckeditor plugin instead.

**Comment by soullivaneuh** [comment]
> But the fckeditor is now outdated and you should use ckeditor through the ckeditor plugin instead.

@bramley Did not see any doc about that. How I am suppose to do that? :thinking:

**Comment by soullivaneuh** [comment]
![image](https://user-images.githubusercontent.com/1698357/100791225-37cde800-3419-11eb-81e4-659d57e52eca.png)

Found it, but I am not able to activate it.

**Comment by soullivaneuh** [comment]
Found. I had to disable the other editor plugin first.

Thanks for the help.
