### ISSUE TITLE
Bad html in file send_core.php

### ISSUE THREAD

**Issue by bramley** [phpList/phplist3#38]
At line 400 of admin/send_core.php some bad html. I think that it meant to be either `<br/>` or `<hr/>`.

```
  if ($sendtest) {
      $sendtestresult = '<r/>';
      if (empty($_SESSION['lasttestsent'])) {
          $_SESSION['lasttestsent'] = 0;
      }
```

**Comment by michield** [comment]
https://github.com/phpList/phplist3/commit/ad5a1b6114e4d0581862acf7a6ba127dd996bea1
