### ISSUE TITLE
Language translation strings

### ISSUE THREAD

**Issue by phpitech** [phpList/phplist3#393]
Again, I'm happy to do a PR to sync these strings but the language translation strings are *way* out of date in git. In fact, equally happy to automate a PR once a month from the translate site.

The locale files @ https://github.com/phpList/phplist3/tree/master/public_html/lists/admin/locale are all over a year old. 

I can see they've not been updated when the last release was generated. Shall I sync the files and add a PR ? 

It would be good to have them reasonably up to date - i'm missing english translation strings here; don't want to raise that as a bug when it's likely already on the translate site!

**Comment by phpitech** [comment]
I had a look at generating this, and observation is that there are strings generated on the translate site that are not in the phplist repo - is that because they are used by phplist.com; e.g. databasestructure.php

**Comment by samtuke** [comment]
@phpitech Thanks for checking -- databasestructure.php is used by phpList, and there shouldn't be any strings from .com on the translate site, though it's possible that they crept in. It's more likely that they are simply strings that are no longer used (such strings are not automatically deleted). Can you give an example of such a string?

**Comment by samtuke** [comment]
@phpitech Regarding syncing strings: that would be great. The strings should be automatically updated after a fresh installation, which is probably why it hasn't been noticed before that they're out of date. But yes, the latest ones should be pulled in during the release process; it looks like that step must be broken. I'll investigate.

**Comment by samtuke** [comment]
Tracking here https://mantis.phplist.org/view.php?id=19385

**Comment by marianaballa** [comment]
This has been marked as resolved on Mantis (on the link above). For future proposals/questions I would recommend the [community forum](https://discuss.phplist.org/) or [Mantis, the phpList bug tracker](https://mantis.phplist.org/my_view_page.php).

Closing this.
