### ISSUE TITLE
GDPR privacy , restrict access to preferences page

### ISSUE THREAD

**Issue by thedayse** [phpList/phplist3#405]
The links for subscribe, preferences etc all use the unique id which is fine and good. However these same pages can also be accessed with an email instead like this
?p=preferences&email=somebody@domain.foo
?p=preferences&unsubscribeemail=somebody@domain.foo
Which seems both unneeded and easy to abuse. Maybe I'm missing something. Any private data the subscriber has supplied, like their name, can be viewed and changed by anyone using just the email address. Is there any need for this?

**Comment by michield** [comment]
Yes, good point. I think it is there as it used to be considered convenient, but now we need to tighten these things up a little. Fancy creating a PR?

**Comment by thedayse** [comment]
Yes I think i can manage a PR later this week. Can I combine it with a fix for #404 or do I need to do 2 PRs?

**Comment by michield** [comment]
Should be fine to combine, I reckon. If you haven't yet, can you also [sign the CLA](https://phplist.com/cla), thanks
