### ISSUE TITLE
Editing email address to another existing email address silently fails

### ISSUE THREAD

**Issue by linucksrox** [phpList/phplist3#409]
When editing an email address and saving, if the new email address matches another existing address, this silently fails and no changes are saved. It would be much more helpful to display some kind of message stating that the email address you typed already exists (maybe even link to that other contact).

**Comment by suelaP** [comment]
I can not replicate the problem on 3.3.9 so I am closing this.
![selection_011](https://user-images.githubusercontent.com/22301998/53184441-4b6ddd00-35fd-11e9-8b59-c790d89e80c9.png)
