### ISSUE TITLE
Stop reusing the same Message-ID for system messages

### ISSUE THREAD

**Issue by da2x** [phpList/phplist3#416]
`Message-ID: systemmessage` is a really bad idea. Messages are expected to always have unique IDs. See also [RFC 5322 §3.6.4](https://tools.ietf.org/html/rfc5322#section-3.6.4).

It causes system messages to get really high spam scores and end up in junk folders. I’m looking at two identical messages at Yahoo! Mail now and they stick  the one with `X-Message-ID: systemmessage` in junk and the one with no difference other than a unique string in the inbox.

Internal logic looks for this specific hardcoded ID for bounce processing.

Quick fix: Set the ID as `phplistinternal-<random-numbers>@[website]` and then change the places that expect that specific ID to look for message IDs that start with `phplistinternal-`. For backwards compatibility, the Message ID `systemmessage` should also be checked for a transitional period and removed in a later release (six months?).

`@example.com` should be added to the end of the Message ID the same time, as it’s the convention for most Message IDs. Older spam filters looked at Message-ID domain mismatches as an indication of a message having been sent through an open relay. Not sure if this is still the case, but phpList should still stick with the convention regarding the format of the Message ID.

**Comment by michield** [comment]
Yes, good point. The main thing is that we use the "systemmessage" during bounce detection, so that would need to change as well.

**Comment by samtuke** [comment]
@xh3n1 Any thoughts on this?

**Comment by michield** [comment]
> I did actually address that in my report.

Yes, true. Thanks. @xh3n1 the above suggestions should make it fairly easy to sort out. We're not doing too much (yet) with bounced system messages.

**Comment by xh3n1** [comment]
@samtuke I also think that X-MessageID should be unique. The above suggestions sound good but it should be tested :)

**Comment by samtuke** [comment]
@da2x A PR addressing this issue would be very welcome.

**Comment by michield** [comment]
Actually, I just realised there's some confusion here. We're not using Message-ID: systemmessage. We use X-MessageID: systemmessage. The RFC refers to Message-ID. W use our own, with the X- prepended, which is perfectly acceptable.

> extension-field =
>                    <Any field which is defined in a document
>                     published as a formal extension to this
>                     specification; none will have names beginning
>                     with the string "X-">

The Message-ID is auto-generated by phpMailer and we don't do anything with it.

Also, we use X-MessageID for the "ID" of the campaign, so it is 1, 2, 3 etc for all subscribers.
