### ISSUE TITLE
Remove non-standard Bounces-To header

### ISSUE THREAD

**Issue by da2x** [phpList/phplist3#419]
The only thing that matters for bounces is the address in the `MAIL FROM` command (as [set here](https://github.com/phpList/phplist3/blob/9ec0dba0b2ccc403d21a2f5fcc0c05b52e5186a6/public_html/lists/admin/PHPMailer/class.smtp.php#L863).) See [RFC 3834](https://tools.ietf.org/html/rfc3834). I checked with half a dozen MTA implementations and none of them had any handling for the `Bounce-To` header. It's non-standard and as far as I can tell no important MTA uses it for anything.

The MTA is responsible for setting the `Return-Path` based on the `MAIL FROM` command. My MTA, OpenSMTPd, does this and this is the only reason why bounces work.

The correct fix here is to remove `Bounces-To` completely. phpList can explicitly set a `Return-Path` but [RFC 3834](https://tools.ietf.org/html/rfc3834) clearly states that is up to the MTA and that the MTA should remove any existing `Return-Path`  headers. Setting this header explicitly can result in duplicated headers. Anti-spam tools are likely to see duplicated `Return-Path` headers as an email forgery attempt.

**Comment by michield** [comment]
Yes, I can't remember where I got that from, and I agree, it's not commonly used. I've merged the PR.
