### ISSUE TITLE
If plugins dir not writable, Manage Plugins should still show plugin list

### ISSUE THREAD

**Issue by mwithheld** [phpList/phplist3#437]
If plugins dir not writable, the Manage Plugins page shows

> The plugin root directory is not writable, please install plugins manually

It should still show the list of plugins because you might want to:

- See what plugins are installed; or
- Enable/disable plugins

I think it worked this way **before** v3.3.5; have not tested 3.3.6.

**Comment by bramley** [comment]
@mwithheld > The plugin root directory is not writable, please install plugins manually

Only the input field to enter a plugin install URL should not be displayed.
The page should then display the installed plugins.  Possibly something is failing and the complete page is not being displayed.

**Comment by suelaP** [comment]
I can not replicate this issue on 3.3.9 with /plugins set to 755 so I will close this. 
![image_2019-02-20_18-40-29](https://user-images.githubusercontent.com/22301998/53112298-33378880-353f-11e9-9dc7-6d18d1aaa7f3.png)
