### ISSUE TITLE
Testing the remote processing secret appears to be duplicated

### ISSUE THREAD

**Issue by bramley** [phpList/phplist3#440]
I'm looking at allowing a plugin to have pages accessed using the remote processing secret, similar to processqueue and processbounces. The test for using the secret parameter is in admin/index.php
```
    } elseif (!empty($_GET['secret']) && ($_GET['page'] == 'processbounces' || $_GET['page'] == 'processqueue' || $_GET['page'] == 'processcron')) {
        //# remote processing call
        $ourSecret = getConfig('remote_processing_secret');
        if ($ourSecret != $_GET['secret']) {
            @ob_end_clean();
            echo 'Error'.': '.s('Incorrect processing secret');
            exit;
        }
```

but admin/actions/processqueue.php and admin/processbounces then repeat the test for the secret parameter e.g.
```
if (isset($_GET['secret'])) {
    $ourSecret = getConfig('remote_processing_secret');
    if ($ourSecret != $_GET['secret']) {
        echo Error(s('Incorrect processing secret'));

        return;
```
@michield  Is this just unnecessary duplication or is there some way that the test in index.php can be bypassed?

**Comment by michield** [comment]
I think that's duplication. Everything runs via index.php

**Comment by bramley** [comment]
Thanks, I have just submitted a pull request to allow this.
