### ISSUE TITLE
Ambiguous date format when checking for an update

### ISSUE THREAD

**Issue by bramley** [phpList/phplist3#505]
This code in file admin/updatelib.php added to check for an update looks to be error prone
```
function lastTimeCheck()
{
    $doCheck = false;
    $currentTime = date('m/d/Y h:i:s', time());
    $lastCheckTime = getConfig('lastcheckupdate');
    $lastTimeFormattedDateTime = new DateTime($lastCheckTime);
    $currentTimeFormattedDateTime = new DateTime($currentTime);
    $interval = $currentTimeFormattedDateTime->diff($lastTimeFormattedDateTime);
    $dDiff = $interval->format('%a');
    if ($dDiff >= '3') {
        $doCheck = true;
    }
    return $doCheck;
}
```
Using the date format 'm/d/Y' is ambiguous,  '1/4/2019' could refer to the first of April or the fourth of January. Instead the ISO format YYYY-MM-DD HH:MM:SS should be used.

Also, there is no need to do this to get the current time as a DateTime object

    $currentTime = date('m/d/Y h:i:s', time());
    $currentTimeFormattedDateTime = new DateTime($currentTime);

`new DateTime()` with no parameter defaults to the current date/time.

**Comment by samtuke** [comment]
Not sure if there is already a mantis issue for this

**Comment by bramley** [comment]
A misunderstanding on my part. php treats a date formatted with '/' characters such as 01/12/2023 as being mm/dd/yy.
