### ISSUE TITLE
Missing files referenced from languages.php

### ISSUE THREAD

**Issue by plane007** [phpList/phplist3#538]
I find that the following files are referenced in this code from line 225 to 245 in languages.php, but they do not exist.

        if (is_file($this->basedir.$this->language.'/'.$page.'.php')) {
            @include $this->basedir.$this->language.'/'.$page.'.php';
        } elseif (!isset($GLOBALS['developer_email'])) {
            @include $this->basedir.$this->defaultlanguage.'/'.$page.'.php';
        }
        $this->lan = $lan;
        $lan = array();

        if (is_file($this->basedir.$this->language.'/common.php')) {
            @include $this->basedir.$this->language.'/common.php';
        } elseif (!isset($GLOBALS['developer_email'])) {
            @include $this->basedir.$this->defaultlanguage.'/common.php';
        }
        $this->lan += $lan;
        $lan = array();

        if (is_file($this->basedir.$this->language.'/frontend.php')) {
            @include $this->basedir.$this->language.'/frontend.php';
        } elseif (!isset($GLOBALS['developer_email'])) {
            @include $this->basedir.$this->defaultlanguage.'/frontend.php';
        }

**Comment by samtuke** [comment]
Yes, this is a known issue being actively worked on. You can track progress here: https://mantis.phplist.org/view.php?id=19895

**Comment by xh3n1** [comment]
@plane007 That's because the translations are handled differently now. Those pages have been legacy pages that have been removed.

**Comment by marianaballa** [comment]
This issue seems not to have any updates since May. For future questions/proposals, I would recommend the [community forum](https://discuss.phplist.org/) or [Mantis, the phpList bug tracker](https://mantis.phplist.org/my_view_page.php).

Closing this.
