### ISSUE TITLE
Error in Docs

### ISSUE THREAD

**Issue by derralf** [phpList/phplist3#540]
on this page: https://www.phplist.org/manual/ch049_api-and-integrations.xhtml it reads
"Delete this folder entirely: public_html/lists/base/cache"
I think it should be:
"... public_html/lists/base/var/cache"

**Comment by xh3n1** [comment]
@derralf That's correct. You can submit a Pull Request here https://github.com/phpList/phplist-manual to update it :)

**Comment by xh3n1** [comment]
fixed in https://github.com/phpList/phplist-manual/pull/12
