### ISSUE TITLE
Updater deploys beta versions

### ISSUE THREAD

**Issue by pridetechdesignllc** [phpList/phplist3#566]
Running 3.4.1 and wanted to upgrade to 3.4.3, the latest "stable". However, the dashboard doesn't have any notifications of the update, and when going to 'update' the only version visible is 3.4.4rc1?

It seems like this probably isn't intentional, or shouldn't be. The "user friendly" updater should only deploy stable version or else should offer choices, wouldn't that make more sense?

**Comment by marianaballa** [comment]
> Running 3.4.1 and wanted to upgrade to 3.4.3, the latest "stable". However, the dashboard doesn't have any notifications of the update, and when going to 'update' the only version visible is 3.4.4rc1?
> 
> It seems like this probably isn't intentional, or shouldn't be. The "user friendly" updater should only deploy stable version or else should offer choices, wouldn't that make more sense?

Hello @pridetechdesignllc,

You can visit Config>Settings and here you can enable/disable the option to receive notifications only for the RCs or only the final releases. 

Additionally, you might want to join the phpList community forum. You can find many useful tips for phpList there. Forum link: https://discuss.phplist.org/

Closing this issue.
