### ISSUE TITLE
Add mail processor which inlines CSS before sending

### ISSUE THREAD

**Issue by liayn** [phpList/phplist3#57]
Any meaningful marketing mail sent today is basically forced to inline CSS in order to deliver the expected view experience in the vast variety of mail clients.

Currently an editor can create a new newsletter in the wysiwyg editor (eg TinyMCE). Even if the template itself already uses proper inlined CSS, the content created by the editor still does not get the inlined CSS of course. (eg headings, hr, etc)

I would really appreciate if you could include such a functionality. Some possible PHP implementations (looking rather up to date) for inlining are:
- https://github.com/jjriv/emogrifier
- https://github.com/christiaan/InlineStyle
- https://github.com/tijsverkoyen/CssToInlineStyles/

Looking forward to your feedback on that matter.
Thanks

**Comment by bramley** [comment]
You might want to look at the Content Areas plugin, which supports inlining CSS https://resources.phplist.com/plugin/contentareas#inline_css_styles. The inlining can be done by Premailer https://github.com/crossjoin/PreMailer as well as emogrifier.

**Comment by liayn** [comment]
@bramley Thanks for the hint. I'm fine with a plugin. Will check that one out.
