### ISSUE TITLE
Unknown image format/encoding

### ISSUE THREAD

**Issue by ghost** [phpList/phplist3#597]
I activated CKEditor as suggested [here](https://discuss.phplist.org/t/the-server-didnt-reply-with-a-proper-xml-data/2243).

However when I try to upload an image I get the following error:

> Unknown image format/encoding.

Apparently after trying a second time the editor sends a request to a non existent file:

http://lists.domain.org/admin/plugins/CKEditorPlugin/kcfinder/plugins/CKEditorPlugin/kcfinder/upload.php

any ideas? Has this anything to do with the apache mime types?

**Comment by bramley** [comment]
@jucajuca It looks like you have the wrong path to KCFinder on the Settings page. Unless you have moved the CKEditor plugin then the path should be left as `plugins/CKEditorPlugin/kcfinder`

![image](https://user-images.githubusercontent.com/3147688/66842535-5944e980-ef63-11e9-81e5-22cb1390a7c8.png)

**Comment by jucajuca** [comment]
I just checked and the path is correct.

**Comment by bramley** [comment]
Thanks. Can you check whether the php GD extension is enabled.

Also, for the second point, what are the values in config.php for
$pageroot and PLUGIN_ROOTDIR

**Comment by jucajuca** [comment]
These are the values of the variables:

$pageroot = '';
define("PLUGIN_ROOTDIR","plugins");

Here is an animation:

![error-screen](https://user-images.githubusercontent.com/24567185/66900384-fe5fd080-effc-11e9-8f8f-0d409d66b008.gif)

**Comment by bramley** [comment]
Can you try uploading from the image browser window instead to see whether that has the same problem?
How do I suspend the animation, it is going too fast to look at?

**Comment by jucajuca** [comment]
after digging into it I found the problem.

in the config file of kcfinder I had to change the drivers for images. Apparently I do not have imagemagick or gmagick. I think phplist should check if the software is installed.

admin/plugins/CKEditorPlugin/kcfinder/conf/config.php

```
    'imageDriversPriority' => "gd", //"imagick gmagick gd"  <<< I changed this.
    'jpegQuality' => 90,
    'thumbsDir' => ".thumbs",
```

**Comment by bramley** [comment]
Thanks for looking into this. The imagick and gmagick are optional and file uploading works when they are not present. Are you sure that you didn't change anything else?

But the plugin should test whether the GD extension is installed, and not allow image upload if it is not. I will look into that.

**Comment by bramley** [comment]
Closing as the raiser's account no longer exists.
