### ISSUE TITLE
SQLite?

### ISSUE THREAD

**Issue by FGasper** [phpList/phplist3#60]
Has anyone tried to make this project use SQLite rather than MySQL?

(And/or, is that a goal of the phplist 4 rewrite?)

**Comment by michield** [comment]
I guess with PL4 we should be storage neutral/unaware

**Comment by michield** [comment]
Sounds like nobody has tried doing that.

**Comment by oliverklee** [comment]
One of the goals of the phpList 4 rewrite indeed is to have it database-agnostic, i.e., also compatible with SQLite.
