### ISSUE TITLE
Demo login doesn't work

### ISSUE THREAD

**Issue by ryancwalsh** [phpList/phplist3#606]
https://demo.phplist.org/lists/admin/ says "Default login is admin, with password phplist" but then says "Incorrect password".

I think this was working within the past week but isn't working today.

**Comment by marianaballa** [comment]
Hi @ryancwalsh 
I just noticed this issue. The login problem on the demo site is now fixed. You can check the phpList demo at https://demo.phplist.org/

You might also want to check the community forum for frequent updates from the phpList community. 

Closing this issue.
