### ISSUE TITLE
Wrong link on Releases

### ISSUE THREAD

**Issue by c-mauderer** [phpList/phplist3#609]
On the https://github.com/phpList/phplist3/releases pages, the link for "Download for production" is wrong. The 'e' is missing in the 'net' of 'sourceforge.net'.

The link is
    https://sourceforge.nt/projects/phplist/files/phplist/
and it should be
    https://sourceforge.net/projects/phplist/files/phplist/

Seems that this is a problem since 3.3.6.

**Comment by suelaP** [comment]
Thanks for pointing this out @c-mauderer 
Fixed :)
