### ISSUE TITLE
Let's move to Bootstrap & Better UI

### ISSUE THREAD

**Issue by petervavro** [phpList/phplist3#62]
How about to use Bootstrap and make UI more friendly ? Personally, I am willing to participate on rebuilding if there is a will. What do you guys think ?

Let me know... Thanks

**Comment by michield** [comment]
Sure, you can help out on https://github.com/phpList/phplist-ui-bootstrap

**Comment by samtuke** [comment]
@petervavro The new theme is available with phpList 3.3-RC4 available on Sourceforge: https://sourceforge.net/projects/phplist/files/phplist-development/

We'd welcome your feedback and contributions!
