### ISSUE TITLE
The admin/locale directory does not match GitHub

### ISSUE THREAD

**Issue by bramley** [phpList/phplist3#634]
In the released phplist the directory admin/locale doesn't match that in GitHub, e.g. admin/locale/en/pagetitles.php which I was looking at to see why a page title was not being found.

Is it meant to or is it redundant now?

**Comment by bramley** [comment]
Also there appear to be frequent updates to .pot files. Are those used now, since moving from Pootle to Weblate?

**Comment by michield** [comment]
I still need to re-build the translation integration. It's currently not fully in action. I'll hope to have that sorted reasonably soon (famous last words)
