### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by dienuet** [phpList/phplist3#638]
Hi team,
While reviewing the source code I found a vulnerability that allows a non-admin user to steal the administrator's cookie. I tested on the latest phplist3.5.2. Let me know if you want detail of this security flaw.
I sent an email to info@phplist.com.
Thanks!

**Comment by suelaP** [comment]
Thanks @dienuet ! We have replied to your email, let's follow up there.

**Comment by djfd** [comment]
any patch pls

**Comment by suelaP** [comment]
> any patch pls
Hi, the fix has been included in phpList 3.5.3
