### ISSUE TITLE
Translation to French not working

### ISSUE THREAD

**Issue by youssefqarri** [phpList/phplist3#647]
Hello,

There are some missing translations (at least, from English to French) : 

- Subscribe to our newsletter in /lists/
- In Menu : 
            Statistics -> **msgbounces**
            System -> **system**

There some others, by these the most obvious ones

**Comment by hiroyuki-sato** [comment]
Hello, @youssefqarri 

I asked a similar question a few weeks ago.
[[IMPORTANT] phpList translations](https://discuss.phplist.org/t/important-phplist-translations/6335) may help
