### ISSUE TITLE
Security problem, at least in 3.5.3

### ISSUE THREAD

**Issue by djfd** [phpList/phplist3#648]
Hello guys,

could anyone explain why is it [here](https://github.com/phpList/phplist3/blob/master/public_html/lists/admin/index.php#L591):
```php
// always allow access to the about page
if (isset($_GET['page']) && $_GET['page'] == 'about') {
    $page = 'about';
    $include = 'about.php';
}
```

All below ```admin``` should be under protection (2F preferable). Why to discover the version, installed plugins, and such to an attackers? Lets show them php paths too (like to web root, log directory etc)...

And moreover, there is even "Sign up to receive news and updates about phpList" a form... Not tested how it behaves though.

There should be very good reasons for doing that, could anyone shed a few light?

Thanks!

**Comment by michield** [comment]
That's there, because it's only informational. But yes, we should hide the plugins and versions on that page.

**Comment by djfd** [comment]
What is intention of notifying everybody about existence phpList installation in the [almost black] box at all? Why to notify attackers about it? At the time when it was done there was some rationale behind it, could you please explain why we should? And especially why to have this particle under admin? Really need a banner? Well, then it should be over admin tree, in userlands. But I sill cannot see why :(

**Comment by michield** [comment]
The rationale is that it will benefit the project, as it links back to the project website and mentions key elements of the project. As we have put a lot of time and effort into something that you get at absolutely no cost, that is the least you can do to contribute to the popularity of the project.

But yes, I agree, that should not undermine the security of the system, so we can make a few changes. But I now also realise that we need to link to that page from the login page, or the public subscribe page, to actually achieve the above. At the moment the page is only found when looking for it. Thanks for pointing that out.

**Comment by michield** [comment]
This commit will now obscure the versions, when viewed without being logged in.
https://github.com/phpList/phplist3/commit/0577b0caf61acdb56f2f657435a11237fc126052
