### ISSUE TITLE
TLD file source not found

### ISSUE THREAD

**Issue by ganti** [phpList/phplist3#649]
The source `https://www.phplist.com/files/tlds-alpha-by-domain.txt`is not avaliable anymore. So new TLDs cant get fetched. 

i found it here: https://github.com/phpList/phplist3/blob/7d9fa6171fb526d8d9621c7351fa482d4371520b/public_html/lists/admin/init.php#L220

**Comment by michield** [comment]
The source file is back now. https://www.phplist.com/files/tlds-alpha-by-domain.txt

**Comment by rettichschnidi** [comment]
https://www.phplist.com/files/tlds-alpha-by-domain.txt.md5 is still missing, causing the update to fail.

**Comment by michield** [comment]
Indeed, thanks for finding that. The file is there now.
