### ISSUE TITLE
TLD file md5 not found

### ISSUE THREAD

**Issue by ganti** [phpList/phplist3#651]
https://www.phplist.com/files/tlds-alpha-by-domain.txt.md5 is still missing, causing the update to fail. _Originally posted by @rettichschnidi in https://github.com/phpList/phplist3/issues/649#issuecomment-618531020_

I also suggest that you run some cronjob, to ensure this file as well as the txt-file is avaliable always and wont be deleted in the future

**Comment by michield** [comment]
Yes, the md5 is there now. We used to have a cron-job, to update the files daily, but a recent server move has dropped that. I will re-instate it.

**Comment by michield** [comment]
The file is back and will be updated daily
