### ISSUE TITLE
installation url returns 404.

### ISSUE THREAD

**Issue by hiroyuki-sato** [phpList/phplist3#657]
Hello, members.

The [INSTALL](https://github.com/phpList/phplist3/blob/master/INSTALL) document contains the following URL. but It returns 404.
https://www.phplist.org/manual/ch028_installation.xhtml

I'll create a PR if someone told me the correct URL.

Best regards.

**Comment by marianaballa** [comment]
That URL redirects actually to the old manual which is no longer in use. Good catch! 

The proper URL is: https://www.phplist.org/manual/books/phplist-manual/page/installing-phplist-manually

**Comment by hiroyuki-sato** [comment]
Hello, @marianaballa 

Thank you for your reply. I created #658.

**Comment by pjohanneson** [comment]
The URL is also incorrect on your website, on https://www.phplist.org/download-phplist/, here (**bold** text indicates the link):

> ## Install
>
> The **phpList user manual** explains how to install it.

**Comment by marianaballa** [comment]
I updated the link @pjohanneson. Thanks for pointing it out!
