### ISSUE TITLE
Cross Site Script Vulnerability on "Configure Attributes" feature in phplist version 3.5.3

### ISSUE THREAD

**Issue by r0ck3t1973** [phpList/phplist3#664]
**Describe the bug**
An authenticated malicious user can take advantage of a Stored XSS vulnerability in the "configure attributes" feature.

**To Reproduce**

1. Login into the panel phplist
2. Go to 'phplist3/lists/admin/?page=attributes&tk=20a8f65277024ee830090611cb93e35d'
3. Click 'Edit Values' -> 'Add new'
4. Insert Payload XSS:
   '><details/open/ontoggle=confirm(1337)>
5. Add new Woonplaats
6. xss alert message

**Expected behavior**
The removal of script tags is not sufficient to prevent an XSS attack. You must HTML Entity encode any output that is reflected back to the page

**Screenhost**
1. login
![login](https://user-images.githubusercontent.com/62001260/82778023-42139600-9e7a-11ea-9699-d019469872f4.PNG)
2. Add new
![Addnew](https://user-images.githubusercontent.com/62001260/82778039-4f308500-9e7a-11ea-84bc-a5022500b6ee.PNG)
3. Insert payload xss
![insert_payload](https://user-images.githubusercontent.com/62001260/82778045-56f02980-9e7a-11ea-96c2-f850f58c4c32.PNG)
4. xss alert message
![xss_mess](https://user-images.githubusercontent.com/62001260/82778053-5fe0fb00-9e7a-11ea-8b77-b3b1ed415003.PNG)

**Desktop (please complete the following information):**
OS: Windows
Browser: All
Version
-----
I Hope you fix it ASAP

**Comment by michield** [comment]
fixed in https://github.com/phpList/phplist3/commit/e22260083e2ae35ae7d57fa5632a9c49db3ce849
