### ISSUE TITLE
Cross Site Scripting Vulnerability on "Import Mail" feature in PHP List

### ISSUE THREAD

**Issue by Songohan22** [phpList/phplist3#667]
**Describe the bug**
An authenticated malicious user can take advantage of a Stored XSS vulnerability in the "Import Mail" feature.
**To Reproduce**

1. Log into the panel.
2. Go to "/admin/?page=import&tk=6adb3efa27ad1baa355bd3b62671c46b"
3. Click "import by uploading a file with emails"
4. Insert payload:
<svg/on<script><script>load=alert('XSS')//</script>
5. Click "Save "
6. View the preview to trigger XSS.
7. View the preview to get in request and such Stored XSS

**Expected behavior**
The removal of script tags is not sufficient to prevent an XSS attack. You must HTML Entity encode any output that is stored back to the page.

**Impact**
Commonly include transmitting private data, like cookies or other session information, to the attacker, redirecting the victim to web content controlled by the attacker, or performing other malicious operations on the user’s machine under the guise of the vulnerable site.

**Screenshots**
![image](https://user-images.githubusercontent.com/29293812/82859123-135ff300-9f40-11ea-8de6-61517bfdc695.png)
![image](https://user-images.githubusercontent.com/29293812/82859195-47d3af00-9f40-11ea-9bfe-80e30160e4c3.png)
![image](https://user-images.githubusercontent.com/29293812/82859225-591cbb80-9f40-11ea-8fb5-5b1db2a5b926.png)

**Desktop (please complete the following information):**
- OS: Windows
- Browser: Firefox
- Version: 76.0.1

**PHP List Version 3.5.5**

**Comment by Songohan22** [comment]
Hi @suaP 
Please review it! Thanks

**Comment by michield** [comment]
Resolved with https://github.com/phpList/phplist3/commit/9c4515c9be32b6cf13f7da67a27db85877083189
