### ISSUE TITLE
[manual] Sending your first campaign contains dead link image URL.

### ISSUE THREAD

**Issue by hiroyuki-sato** [phpList/phplist3#670]
Hello, @marianaballa (It seems that you are the maintainer [PHPlist manual](https://www.phplist.org/manual/books/phplist-manual/page/sending-your-first-campaign))

[Sending your first campaign](https://www.phplist.org/manual/books/phplist-manual/page/sending-your-first-campaign) contains a dead link image URL.

Please see this thread in more detail.
https://discuss.phplist.org/t/image-not-found-sending-your-first-campaign-page/6246/6

I can remove it, but can't fix it. I'm not sure correct URL

Best regards.

**Comment by marianaballa** [comment]
Hello @hiroyuki-sato ! Many thanks for reporting this. I responded on the phpList community forum as well. I could not see the image as well when switching to a private tab. 

I'll invastigate this!

Best,
Mariana

**Comment by hiroyuki-sato** [comment]
Hello, @marianaballa. Thank you for your reply. I confirmed that this issue resolved.
(Martin updated that page). Thanks!
