### ISSUE TITLE
Cross Site Scripting Vulnerability on "Manage administrators" feature in PHPList  3.5.3, 3,5.4

### ISSUE THREAD

**Issue by Songohan22** [phpList/phplist3#671]
**Describe the bug**
An authenticated malicious user can take advantage of a Stored XSS vulnerability in the "Manage administrators" feature.
**To Reproduce**

1. Log into the panel.
2.  Go to "/admin/?page=admins&tk=569e1f6f9e6b3a9abd9046ff57e34aaf" 
3. Click "Manage administrators"
4. Click "admin" edit infomation admin.
5. Insert payload:
     "><svg/onload=alert(/XSS/)>
![image](https://user-images.githubusercontent.com/29293812/83284012-4e934800-a206-11ea-900d-45d9ebefbcd8.png)
      // # "><svg/onload=prompt(/SonGohan22/)>
6. Click "Save Changes"
7. View the preview to trigger XSS.
8. View the preview to get in request and such Stored XSS

**Expected behavior**
The removal of script tags is not sufficient to prevent an XSS attack. You must HTML Entity encode any output that is stored back to the page.

**Impact**
Commonly include transmitting private data, like cookies or other session information, to the attacker, redirecting the victim to web content controlled by the attacker, or performing other malicious operations on the user’s machine under the guise of the vulnerable site.

 **Screenshots**
![image](https://user-images.githubusercontent.com/29293812/83283300-3111ae80-a205-11ea-8f7d-c6d5b70560fb.png)
 Insert payload
![image](https://user-images.githubusercontent.com/29293812/83283469-78983a80-a205-11ea-85d0-2bc041a1f1e4.png)
Click "Save Changes" -> Click "List of administrator" -> View Stored XSS
![image](https://user-images.githubusercontent.com/29293812/83283920-2e638900-a206-11ea-818c-9c158ee6ed66.png)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Firefox
- Version: 76.0.1

**Comment by michield** [comment]
Resolved with https://github.com/phpList/phplist3/commit/b2d581fa9d474927f3e85e1d0f020f69b95c3312
