### ISSUE TITLE
Missing 3.5.4 release 

### ISSUE THREAD

**Issue by hiroyuki-sato** [phpList/phplist3#673]
Hello, developers.

As far as I know, The latest version is 3.5.4.
But the latest is still 3.5.3 in [this page](https://github.com/phpList/phplist3/releases)

Is missing tag update?

<img width="1038" alt="スクリーンショット 2020-06-01 11 22 28" src="https://user-images.githubusercontent.com/767650/83370461-6fbc8a00-a3fa-11ea-8154-10ee97a49e8d.png">

Best regards.

**Comment by suelaP** [comment]
@hiroyuki-sato well spotted. It has now been published there too.

**Comment by hiroyuki-sato** [comment]
Thank you!
