### ISSUE TITLE
Cross Site Scripting Vulnerability on "Send a campaign" feature in PHPList 3.5.4

### ISSUE THREAD

**Issue by Songohan22** [phpList/phplist3#676]
**Describe the bug**
An authenticated malicious user can take advantage of a Stored XSS vulnerability in the "Send a campaign" feature.
**To Reproduce**

1. Log into the panel.
2. Go to "/admin/?page=send&id=3&tk=311902f27f63cc4f7466fc56ca0e916b&tab=Finish"
3. Insert payload: 
![image](https://user-images.githubusercontent.com/29293812/83870606-bdb5f280-a758-11ea-98f1-cf401ace13f7.png)
// # "><svg/onload=prompt(/SonGohan22/)>
"><svg/onload=alert(document.domain)>
4. Click "Save and continue editing"
5. View the preview to trigger XSS.
6. View the preview to get in request and such Stored XSS.

**Expected behavior**
The removal of script tags is not sufficient to prevent an XSS attack. You must HTML Entity encode any output that is stored back to the page.

**Impact**
Commonly include transmitting private data, like cookies or other session information, to the attacker, redirecting the victim to web content controlled by the attacker, or performing other malicious operations on the user’s machine under the guise of the vulnerable site.

**Screenshots**
![phplist22](https://user-images.githubusercontent.com/29293812/83871779-e7701900-a75a-11ea-8271-c2d4fcb05339.png)
![phplist23](https://user-images.githubusercontent.com/29293812/83871874-18e8e480-a75b-11ea-8966-d44cafc05e48.png)
Insert payload
![phplist24](https://user-images.githubusercontent.com/29293812/83872013-5fd6da00-a75b-11ea-83bb-4858515ec09a.png)
Trigger XSS
![phplist25](https://user-images.githubusercontent.com/29293812/83872340-fe633b00-a75b-11ea-935d-99133636f850.png)
![phplist26](https://user-images.githubusercontent.com/29293812/83872343-015e2b80-a75c-11ea-8866-49b556faae39.png)
![phplist27](https://user-images.githubusercontent.com/29293812/83872350-04591c00-a75c-11ea-8535-65da08a85bd7.png)

**Desktop (please complete the following information):**
- OS: Ubuntu
- Browser: Firefox
- Version: 76.0.1

**Comment by Songohan22** [comment]
Hi @michield @suelaP
Please review it! Thanks

**Comment by michield** [comment]
Resolved with https://github.com/phpList/phplist3/commit/5388df4079132b27b158feac39f02a827ce1239a
