### ISSUE TITLE
Cross Site Scripting Vulnerability on "Setting" feature in PHPList 3.5.4

### ISSUE THREAD

**Issue by Songohan22** [phpList/phplist3#677]
**Describe the bug**
An authenticated malicious user can take advantage of a Stored XSS vulnerability in the "Setting" feature.
**To Reproduce**

1. Log into the panel.
2. Go to "http://son.labs.com/admin/?page=configure&tk=5e8163f644e4f4d6c4779e60048e8459"
3. Click Edit "Name of the organisation"
4. Insert payload:
           <svg/on<script><script>load=alert(/SonGohan22/)//</script>
           "><svg/onload=alert(document.domain)>
           // # "><svg/onload=prompt(document.cookie)>
5. Click "Save changes"
6.  Access "http://son.labs.com"
7. View the preview to trigger XSS.
8. View the preview to get in request and such Stored XSS.

**Expected behavior**
The removal of script tags is not sufficient to prevent an XSS attack. You must HTML Entity encode any output that is stored back to the page.

**Impact**
Commonly include transmitting private data, like cookies or other session information, to the attacker, redirecting the victim to web content controlled by the attacker, or performing other malicious operations on the user’s machine under the guise of the vulnerable site.

**Screenshots**
![phplist1](https://user-images.githubusercontent.com/29293812/83897578-f61cf700-a77f-11ea-9764-6c82a0374b27.PNG)
![image](https://user-images.githubusercontent.com/29293812/83897922-6cb9f480-a780-11ea-9549-667ecf084b23.png)
![image](https://user-images.githubusercontent.com/29293812/83898092-a25edd80-a780-11ea-8e2c-cb95e00a8001.png)

**Desktop (please complete the following information):**
- OS: Ubuntu
- Browser: Firefox
- Version: 76.0.1

**Comment by Songohan22** [comment]
Hi @michield @suelaP
Please review it! Thanks

**Comment by michield** [comment]
Well, this one is slightly contradictory. If we disallow JS in the configuration, we should also disallow it in the subscribe pages, which would counter the whole process of building pages.

It's a bit like, you can't put any HTML or JS in the content of a CMS. But that's the whole point of having a CMS. 

We can sanitise this particular variable, but then pageheader and pagefooter will need to allow HTML and JS, and therefore would also have this issue.

**Comment by michield** [comment]
This particular situation is resolved with https://github.com/phpList/phplist3/commit/6e1379fbf55b1b4ab9c7d63a5454695419e3ba1c

However, the same can be achieved on the pageheader and pagefooter config values.

**Comment by Songohan22** [comment]
@michield 
 Yep...You work very well
Thank,
