### ISSUE TITLE
Cross Site Scripting Vulnerability on "Import subscribers" feature in PHPList 3.5.4 upload file SVG.

### ISSUE THREAD

**Issue by Songohan22** [phpList/phplist3#678]
**Describe the bug**
An authenticated malicious user can take advantage of a Stored XSS vulnerability in the "Import subscribers" feature.
**To Reproduce**

1. Log into the panel.
2. Go to "/admin/?page=import2&tk=93e3e3e3bbd0bd48b788a384c549813b"
3. Click "Browse"
4. Import payload file SVG: 
![image](https://user-images.githubusercontent.com/29293812/83971042-440e3800-a903-11ea-9542-7c005adc7d32.png)
5. Click button "Import"
6. Click select "Email".
7. Click button "CONTINUE" 
8. View the preview to trigger XSS.
9. View the preview to get in request and such Stored XSS.

**Expected behavior**
The removal of script tags is not sufficient to prevent an XSS attack. You must HTML Entity encode any output that is stored back to the page.

**Impact**
Commonly include transmitting private data, like cookies or other session information, to the attacker, redirecting the victim to web content controlled by the attacker, or performing other malicious operations on the user’s machine under the guise of the vulnerable site.
**Screenshots**
![phplist222](https://user-images.githubusercontent.com/29293812/83971596-5ccc1d00-a906-11ea-9447-b2abe397c7df.PNG)
![phplist223](https://user-images.githubusercontent.com/29293812/83971598-605fa400-a906-11ea-9ef1-7737d178c883.PNG)
![phplist224](https://user-images.githubusercontent.com/29293812/83971602-62c1fe00-a906-11ea-87ca-1a4ddd9b5ae2.PNG)
Trigger XSS
![phplist_final](https://user-images.githubusercontent.com/29293812/83971604-66ee1b80-a906-11ea-839f-5bfa0a4c55d0.PNG)
**Desktop (please complete the following information):**
- OS: Ubuntu
- Browser: Firefox
- Version: 76.0.1

**Comment by Songohan22** [comment]
Hi @michield @suelaP
Please review it! Thanks

**Comment by michield** [comment]
This is resolved with https://github.com/phpList/phplist3/commit/bf445db5b0548d09079cf45ed89867fd79e6bf56
