### ISSUE TITLE
Cross Site Scripting Vulnerability on "Send a campaign" feature in PHPList 3.5.4

### ISSUE THREAD

**Issue by Songohan22** [phpList/phplist3#679]
**Describe the bug**
An authenticated malicious user can take advantage of a Stored XSS vulnerability in the "Send a campaign" feature.
**To Reproduce**

1. Log into the panel.
2. Go to "/admin/?page=send&id=5&tk=93e3e3e3bbd0bd48b788a384c549813b"
3. Select "Send a webpage "
4. Insert payload:
              // # "><svg/onload=prompt(/SonGohan22/)>
             "><svg/onload=alert(document.domain)>
![image](https://user-images.githubusercontent.com/29293812/83972982-89376780-a90d-11ea-942b-959e62373dce.png)
5. Click "Save as draft"
6.  Click Draft campaigns  save as draft step 5.
7.  View the preview to trigger XSS.
8.  View the preview to get in request and such Stored XSS.

**Expected behavior**
The removal of script tags is not sufficient to prevent an XSS attack. You must HTML Entity encode any output that is stored back to the page.

**Impact**
Commonly include transmitting private data, like cookies or other session information, to the attacker, redirecting the victim to web content controlled by the attacker, or performing other malicious operations on the user’s machine under the guise of the vulnerable site.

**Screenshots**
![226_php](https://user-images.githubusercontent.com/29293812/83973588-bede4f80-a911-11ea-96b9-1a32b6621d42.PNG)
![231_php](https://user-images.githubusercontent.com/29293812/83973602-e46b5900-a911-11ea-8a6b-9287f1a9623e.PNG)
![233_php](https://user-images.githubusercontent.com/29293812/83973603-e6cdb300-a911-11ea-90e3-e2a44f0f135a.PNG)
Trigger XSS
![228_php](https://user-images.githubusercontent.com/29293812/83973613-f6e59280-a911-11ea-8ad1-9d9b78fbe3e1.PNG)
![229_php](https://user-images.githubusercontent.com/29293812/83973617-fa791980-a911-11ea-953b-2ba6279f2492.PNG)
![230_php](https://user-images.githubusercontent.com/29293812/83973620-fcdb7380-a911-11ea-92c7-511b98e12fcf.PNG)

**Desktop (please complete the following information):**
- OS: Ubuntu
- Browser: Firefox
- Version: 76.0.1

**Comment by Songohan22** [comment]
Hi @michield @suelaP
Please review it! Thanks

**Comment by michield** [comment]
Resolved with https://github.com/phpList/phplist3/commit/a9ee6fde7846238506fd542ec77b8b4287951f13

**Comment by Songohan22** [comment]
Hi Team Security phplist3.

You can a CVE ID assigned :D

Thanks you!
