### ISSUE TITLE
processqueue currently uses sleep() function, why not use meta refresh instead?

### ISSUE THREAD

**Issue by sculptex** [phpList/phplist3#68]
php sleep() function keeps the script active and so any simultaneous access to the website from the same computer will likely be very slow. A meta refresh or perhaps another type of scripting for the delay would behave as idle and not remain active, freeing resources.
So header would contain something like;
`<META HTTP-EQUIV="Refresh" <?php echo"CONTENT=\"$delay; URL=$site_url/lists/admin/?page=processqueue\"; ?>">`

**Comment by michield** [comment]
can you point to the code location that you are referring to?

**Comment by sculptex** [comment]
admin/action/processqueue.php line 299
`sleep($delaytime);`

**Comment by michield** [comment]
the reason it uses sleep is that it may not be in a browser context. In many cases it runs from commandline. https://www.phplist.org/manual/ch035_methods-of-sending-browser-cron-command-line.xhtml

**Comment by sculptex** [comment]
That line only runs when you are not calling from command line, see the condition on the prior line
`if (empty($GLOBALS['inRemoteCall']) && empty($GLOBALS['commandline'])) {`
So I guess I should have been more specific when I raised this issue, but it is still valid. Lots of people complain, particularly on laptops that sleep() will unnecessarily burden the processor, it also (usually) prevents or slows to a crawl any other browsing you are doing on the same computer and browser on that server at the same time.

**Comment by michield** [comment]
https://github.com/phpList/phplist3/blob/master/public_html/lists/admin/actions/processqueue.php#L298

Ok, true. Fair enough, that can be addressed

**Comment by sculptex** [comment]
Proposed an alternative approach, using javascript at https://discuss.phplist.org/t/during-browser-send-processqueue-use-javasript-timeout-function-instead-of-php-sleep/2642

**Comment by michield** [comment]
best is to send a PR.

**Comment by sculptex** [comment]
Thanks, see https://github.com/phpList/phplist3/pull/157
