### ISSUE TITLE
Incorrect CLICKTRACK description in config_extended.php.

### ISSUE THREAD

**Issue by hiroyuki-sato** [phpList/phplist3#687]
Hello, developers

I found an incorrect `CLICKTRACK` description in `config_extended.php`. 
It says that `CLICKTRACK` is zero by default. But It's 1 by default .

https://github.com/phpList/phplist3/blob/1166e816201156fbf391fc54cb500e58466d1634/public_html/lists/admin/init.php#L418-L420

```
// Click tracking
// If you set this to 1, all links in your emails will be converted to links that
// go via phpList. This will make sure that clicks are tracked. This is experimental and
// all your findings when using this feature should be reported to mantis
// for now it's off by default until we think it works correctly
define('CLICKTRACK', 0);
```

https://github.com/phpList/phplist3/blob/master/public_html/lists/config/config_extended.php#L636-L641

Source: 1166e816201156fbf391fc54cb500e58466d1634

**Comment by suelaP** [comment]
Hi @hiroyuki-sato you are right.   Well spotted!
The config_extended.php file is supposed to provide documentation on config additions that can be used with phpList and that information is outdated and not correct. For default values on config settings you can also check here: resources.phplist.com. 

Do you feel like creating a PR for the fix?

**Comment by hiroyuki-sato** [comment]
Hello, @suelaP Thank you for your comment. 
I create #688. Please take a look when you get a chance.

**Comment by suelaP** [comment]
@hiroyuki-sato thank you for your contribution! Merged :)

**Comment by hiroyuki-sato** [comment]
Thanks!
