### ISSUE TITLE
Updater: JavaScript error

### ISSUE THREAD

**Issue by nepomuc** [phpList/phplist3#705]
When calling the updater via https://example.com/lists/updater/ a JavaScript error pops up in the console. There seems to be a mistake with counting the steps, or the server response "-1" is not correct. Looking at the current JavaScript code it would have to be 0 to work. But not it returns -1. Rhe first line in executeNextStep() adds 1 to it which results in 0, but since stepActionMap in setCurrentActionItem() counts by beginning at 1 the entire updater doesn't work.

![image](https://user-images.githubusercontent.com/864660/97549535-cc839700-19d0-11eb-84b9-fa952ef36bc9.png)

**Comment by nepomuc** [comment]
I there someone who can fix this?

**Comment by michield** [comment]
Please report this to the updater project
https://github.com/phpList/updater
