### ISSUE TITLE
Differences between releases on GitHub and Sourceforge

### ISSUE THREAD

**Issue by nepomuc** [phpList/phplist3#716]
I just compared the two ZIP files from https://sourceforge.net/projects/phplist/files/latest/download and https://github.com/phpList/phplist3/archive/3.5.8.zip which both seem to provide phplist 3.5.8, but the ZIP files' contents differ. Why? What's the correct ZIP file to use?

**Comment by michield** [comment]
You need to use the one from https://www.phplist.com/download-phplist/

See also https://github.com/phpList/phplist3/releases/tag/3.5.8
