### ISSUE TITLE
How to embed uploaded images

### ISSUE THREAD

**Issue by nepomuc** [phpList/phplist3#717]
There's the config option `EMBEDEXTERNALIMAGES` to embed external images right into the email. But images uploaded inside the editor, which are stored in `UPLOADIMAGES_DIR` aren't embedded into the emails. Is there an option to activate embedding for internal images, too?

**Comment by michield** [comment]
Images uploaded to templates will be embedded. The idea is that you want the template to have the basics to "look nice" even off-line, and then the content images are added by downloading when needed.

In general you'd want to avoid embedding too many images, particularly when they are big. It would slow down sending, and take up more bandwidth than necessary. Embedded images always get transferred. Remote images only get transferred on demand (ie when a subscriber opens the emails).

**Comment by michield** [comment]
Questions like this are better placed in https://discuss.phplist.org/
