### ISSUE TITLE
CLI: config file autodiscovery doesn't work as expected

### ISSUE THREAD

**Issue by jwindhager** [phpList/phplist3#719]
https://github.com/phpList/phplist3/blob/master/public_html/lists/admin/index.php#L68

I think lines 68 and 70 should be changed from:

`$configfile = '../config/config.php';`

to:

`$configfile = dirname(__FILE__).'../config/config.php';`

**Comment by michield** [comment]
Can you explain in what situation that change has made things work better?

**Comment by jwindhager** [comment]
When calling the admin's index.php from command-line, with the change, the location of the config file (if not explicitly specified with `-c`) does not depend on the current working directory anymore.

**Comment by michield** [comment]
ok, sure, but that's what the -c parameter is for.

**Comment by michield** [comment]
If you want to submit a PR, you're very welcome. Please make sure to sign the [CLA](https://www.phplist.com/cla) before you do.

**Comment by michield** [comment]
Resolved with #977
