### ISSUE TITLE
Crazy issue which i've lost 5 hours of my life with :/

### ISSUE THREAD

**Issue by miraclebg** [phpList/phplist3#721]
I've found a very strange issue which drove me crazy...

The command: phplist -pinitialise - to initialize the db from cmd (saw it from the docker stuff) works ONLY if the following is defined in the config:

$developer_email = 'some@email.com'

Why is that? I've had to debug the hell out of everything to find it out...

**Comment by michield** [comment]
this was recently already reported in #718

**Comment by miraclebg** [comment]
Damn so much cursing today and it was already reported :)

**Comment by michield** [comment]
See #812
