### ISSUE TITLE
Upgrading from 3.6.0-RC1 to 3.6.0 did not apply the change to the database schema

### ISSUE THREAD

**Issue by bramley** [phpList/phplist3#728]
I upgraded to 3.6.0-RC1 last week then upgraded to 3.6.0 yesterday. After the database update I checked the definition of the processed column and it had not changed.

In upgrade.php the database version read from the config table is manipulated by removing "-RC1"

    if (preg_match('/(.*?)-/', $dbversion, $regs)) {
        $dbversion = $regs[1];
    }

This makes the check for applying the scheme change to fail because the database appears to already be the correct version

    if (version_compare($dbversion, '3.6.0','<')) {
        Sql_Query("alter table {$GLOBALS['tables']['message']} change column processed processed integer ");
    }

I'm not sure why the version is being changed in this way.

**Comment by michield** [comment]
I did not expect this change to go into 3.6.0, because the RC had already been released, so this shouldn't have gone in.
I made it apply only for higher than 3.6.0

I guess we need to change the logic for 3.6.1 then. That's slightly tricky.

**Comment by michield** [comment]
Actually, it's not tricky at all. Running the same query again doesn't throw an error, so we can just re-apply this in 3.6.1
