### ISSUE TITLE
Unable to modify precacheMessage() function in sendemaillib.php

### ISSUE THREAD

**Issue by jaspreetAxt** [phpList/phplist3#731]
Hey, 
I am customizing this phplist Application. 
In Sendemaillib.php there is function used and I want to pass email variable into it. But unfortunately by passing any third argument in this function. It just stopped working. 
What I am doing is : 
 ```
if (!precacheMessage($messageid,$email, $forwardContent)) {
            unset($cached[$messageid]);
            logEvent('Error loading message ' . $messageid . '  in cache');

            return 0;
 }
```

Then Where it defines
`function precacheMessage($messageid,$email, $forwardContent = 0) { // Stopped working`

**Comment by michield** [comment]
No further updates, closing
