### ISSUE TITLE
Add new language

### ISSUE THREAD

**Issue by pYFZOS5** [phpList/phplist3#747]
https://translate.phplist.org/projects/phplist/phplist3/
Unable to add new langauges. This is a request to add "Sinhala" language.

**Comment by marianaballa** [comment]
Generally, you should be able to add new languages at the bottom of this page: https://translate.phplist.org/projects/phplist/phplist3/
There is a button "Start a new translation" where you can add a new language to the languages' list. 

Either way, I added Sinhala for you. :) You can check it here: https://translate.phplist.org/projects/phplist/phplist3/si/

**Comment by pYFZOS5** [comment]
> Generally, you should be able to add new languages at the bottom of this page: https://translate.phplist.org/projects/phplist/phplist3/
> There is a button "Start a new translation" where you can add a new language to the languages' list.

No. it doesn't work, that button grayed out. You can reproduce it; register new account using new email address and try to click that button (your team might mistaken and restricted permission)

**Comment by marianaballa** [comment]
Great feedback! I thought every user was able to add a new language. I will check default permissions for new users.

**Comment by michield** [comment]
Can this be resolved?

**Comment by michield** [comment]
Language has been added https://translate.phplist.org/projects/phplist/phplist3/si/
