### ISSUE TITLE
Facing Issue: Could not instantiate mail function on localhots

### ISSUE THREAD

**Issue by software32** [phpList/phplist3#749]
Hi, I am new on this, i have successfully setup all the thing, but my campaign is not sending emails. So please guide me.

Error sending email to xyz@example.com Could not instantiate mail function.

**Comment by marianaballa** [comment]
Hello,

you might want to have a look at the phpList community forum. There are plenty of topics similar to your issue and the forum members might have already resolved it. 

Have a look here: https://discuss.phplist.org/
