### ISSUE TITLE
🚨 Potential Cross-site Scripting (XSS) - Stored

### ISSUE THREAD

**Issue by huntr-helper** [phpList/phplist3#765]
👋 Hello, @michield, @bramley, @xh3n1 - a potential high severity Cross-site Scripting (XSS) - Stored vulnerability in your repository has been disclosed to us.

#### Next Steps

1️⃣  Visit **https://huntr.dev/bounties/1-other-phpList/phplist3** for more advisory information.

2️⃣  **[Sign-up](https://huntr.dev/)** to validate or speak to the researcher for more assistance.

3️⃣ Propose a patch or outsource it to our community - whoever fixes it gets paid.

---

#### Confused or need more help?

- Join us on our **[Discord](https://huntr.dev/discord)** and a member of our team will be happy to help! 🤗

- Speak to a member of our team: @JamieSlome

---

*This issue was automatically generated by [huntr.dev](https://huntr.dev) - a bug bounty board for securing open source code.*

**Comment by michield** [comment]
Yes, I can replicate that. I'll push a fix in a bit.

**Comment by michield** [comment]
Resolved with #766

**Comment by JamieSlome** [comment]
@michield - are you able to confirm the patch on the advisory page?

https://huntr.dev/bounties/1-other-phpList/phplist3

**Comment by michield** [comment]
Yes, the fix is https://github.com/phpList/phplist3/pull/766

this will be released shortly. It's a shame that huntr.dev is not using responsible disclosure.

**Comment by JamieSlome** [comment]
@michield - great, thanks for the heads up!

We now support responsible disclosure! If you would like, I can move this repository over to co-ordinated disclosure, meaning that all new reports will be visible to you, and the reporter?

Would you like me to go ahead and do this?

Cheers! 🍰

**Comment by michield** [comment]
Thanks, I'll work on a security policy, but I would imagine responsible disclosure would be the default when there isn't one.
