### ISSUE TITLE
Plugins not included in the GitHub release candidate zip and gz files

### ISSUE THREAD

**Issue by bramley** [phpList/phplist3#767]
The files for 3.6.3-RC1 and RC2 on GitHub do not contain the plugins,  https://github.com/phpList/phplist3/releases

Whereas the files on Sourceforge do have the plugins, https://sourceforge.net/projects/phplist/files/phplist-development/3.6.3-RC2/

**Comment by michield** [comment]
Yes, that's because the files on Github are just a zip of the code, and that's not enough.

The files on SF are generated here: https://github.com/phpList/phplist3/runs/2612344977?check_suite_focus=true

We can't use the Github download option and we need to make clear not to fetch those files.

**Comment by bramley** [comment]
@marianaballa The announcement needs to be changed to remove the reference to downloading from GitHub.

> Today, a second Release Candidate is launched! v3.6.3-RC2 includes security fixes.
> You can download and install phpList v3.6.3-RC2 from SourceForge or GitHub.
>

**Comment by michield** [comment]
Yes, that's a good point. We need to stop people from downloading from Github, as that's not going to be a complete version. It won't have the theme, plugins or translations.

**Comment by marianaballa** [comment]
> @marianaballa The announcement needs to be changed to remove the reference to downloading from GitHub.
> 
> > Today, a second Release Candidate is launched! v3.6.3-RC2 includes security fixes.
> > You can download and install phpList v3.6.3-RC2 from SourceForge or GitHub.

I edited the announcement. Thanks for pointing it out.
