### ISSUE TITLE
🚨 Potential Security Vulnerability

### ISSUE THREAD

**Issue by ranjit-git** [phpList/phplist3#769]
Hello, @michield @bramley @xh3n1   - Three potential high severity security vulnerability in your repository has been disclosed to huntr.

Visit report url and validate them 
https://huntr.dev/bounties/2-other-phpList/phplist3/
https://huntr.dev/bounties/3-other-phpList/phplist3/
https://huntr.dev/bounties/4-other-phpList/phplist3/

**Comment by michield** [comment]
Thanks. The first two are not really issues. The last one is, and I will create a PR.

**Comment by michield** [comment]
Resolved with #771
