### ISSUE TITLE
phplist 3.6.3 (tgz) has wrong md5 sum

### ISSUE THREAD

**Issue by nblock** [phpList/phplist3#773]
The archive https://sourceforge.net/projects/phplist/files/phplist/3.6.3/phplist-3.6.3.tgz has md5sum `64fb06c1056c774fa9a4ea5c8e72b1a2` while the provided checksum file at https://sourceforge.net/projects/phplist/files/phplist/3.6.3/phplist-3.6.3.md5 has `79fece4b563b3cc466e5cc974b38705f`

**Comment by michield** [comment]
Thanks, I'll try to find out what happened.

**Comment by michield** [comment]
I double checked, but I still get the same md5sum as the one uploaded

md5sum phplist-3.6.3.tgz
79fece4b563b3cc466e5cc974b38705f  phplist-3.6.3.tgz

**Comment by michield** [comment]
Ah, but the one from SF is wrong. Ok, I will re-upload.

**Comment by michield** [comment]
The SF upload keeps failing. Some error on SF.

**Comment by michield** [comment]
Ok, I think it's fine now. Thanks for reporting. We will update the process to check this when uploading.
