### ISSUE TITLE
phplist 3.6.3 doesn't include the latest Trevelin theme

### ISSUE THREAD

**Issue by bramley** [phpList/phplist3#774]
The admin/ui/phplist-ui-bootlist directory isn't the current code in the phplist-ui-bootlist repository. In particular pull request 119 https://github.com/phpList/phplist-ui-bootlist/pull/119 which changed file mainmenu.php is not included.

**Comment by michield** [comment]
Ah, that's annoying. Strange that this didn't come out in RC testing.

Ok, yet another issue on the new build process.

**Comment by bramley** [comment]
This appears to be fixed in 3.6.4-RC3.
