### ISSUE TITLE
The new release process has not included all of the necessary files for the REST API

### ISSUE THREAD

**Issue by bramley** [phpList/phplist3#776]
Trying to use the phplist 4 REST API fails with an error 

`[10-Jun-2021 14:19:40 Europe/London] PHP Fatal error:  Uncaught RuntimeException: There is no composer.json in the supposed application root "/home/dcameron/public_html/lists/base". in /home/dcameron/public_html/lists/base/vendor/phplist/core/src/Core/ApplicationStructure.php:51`

In the 3.6.3 release there are fewer files in the lists/base directory compared to the 3.6.2 release. In particular the composer.json file is required, but it may be safest just to include the same files as previously.

This was reported in the user forum https://discuss.phplist.org/t/how-can-i-access-the-api-with-version-3-6-3/7481

**Comment by michield** [comment]
Interesting. I didn't realise composer.json is needed for the application.
The cleaning up is done here: https://github.com/phpList/phplist3/blob/master/.github/workflows/build-release.yml#L166

I'll update it to leave composer.json in place.

**Comment by michield** [comment]
The issue reported in the forums may be different though. They report a 404. 

I should get started on some automated tests on the API to ensure it continues to work,

**Comment by bramley** [comment]
> They report a 404.

Yes, that foxed me until I realised that `/lists/api/v2` needed to be `/lists/api/v2/` for it to be matched by the rewrite rule in .htaccess.

**Comment by michield** [comment]
So, is composer.json still needed? I thought it was a build related file, but not involved in run-time.

**Comment by bramley** [comment]
I meant that I got a 404 when I used the incorrect URL without a trailing '/'. With the correct URL the exception is thrown.

**Comment by bramley** [comment]
This appears to be fixed in 3.6.4-RC3.
