### ISSUE TITLE
Phplist 3.6.3 - blank dashboard page

### ISSUE THREAD

**Issue by MouchaTo** [phpList/phplist3#780]
After authentication for the administration interface, the dashboard page is empty.
By modifying header_minified.inc
print _topMenu ();
to
print topMenu ();
it looks ok on php 8.0.5

**Comment by michield** [comment]
Interesting. Thanks for reporting. Can I confirm you're saying this error happens with PHP 8.0.5?

**Comment by MouchaTo** [comment]
Yes, php-fpm
PHP 8.0.5 
Copyright (c) The PHP Group
Zend Engine v4.0.5, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.5, Copyright (c), by Zend Technologies

I do not have the skills to discover the causes

**Comment by michield** [comment]
Hmm, not sure this can be replicated. The CI pipeline has PHP 8.0.7 and works fine:

https://github.com/phpList/phplist3/runs/2956932842?check_suite_focus=true#step:13:12

**Comment by bramley** [comment]
This may be a consequence of #774

**Comment by MouchaTo** [comment]
by downloading again the theme bootlist, everything works without modifying the file header_minified.inc

**Comment by michield** [comment]
This is now presumably resolved. Re-open if not.
