### ISSUE TITLE
The  updater should disable DISPLAY_ERRORS

### ISSUE THREAD

**Issue by veltsumatti** [phpList/phplist3#783]
If DISPLAY_ERRORS = On in php.ini, the updater process stops at phase 10.

See https://discuss.phplist.org/t/automatic-update-from-3-6-2-to-3-6-3-fails/7546

**Comment by michield** [comment]
Presumably resolved with phpList/updater#89

Should make it to the next release

Also, in general it's best to only have display errors on when developing.
