### ISSUE TITLE
Difficulty to import emails

### ISSUE THREAD

**Issue by neobie** [phpList/phplist3#792]
When upload failed, no further guideline given.
Either no error message, or no advice on the file size limit.
Should advise on configuration on php param too.

**Comment by michield** [comment]
Can you give some more detail?

Eg https://demo.phplist.org/lists/admin/?page=import2

![image](https://user-images.githubusercontent.com/569843/128630722-de399e6e-4683-42e4-a680-3edd961420a9.png)

**Comment by michield** [comment]
closing for lack of response
