### ISSUE TITLE
non-free `progressbar.js`

### ISSUE THREAD

**Issue by onlyjob** [phpList/phplist3#8]
During packaging of _phpList_ for Debian I've noticed that `public_html/lists/admin/js/progressbar.js` <sup>[1]</sup> is non-free because its redistribution is prohibited, see
http://www.dynamicdrive.com/notice.htm

Please consider removing proprietary script. Thanks.

[1]: https://github.com/phpList/phplist3/blob/master/public_html/lists/admin/js/progressbar.js

**Comment by michield** [comment]
will do, thanks for finding that.

**Comment by michield** [comment]
done f3047de9d0db19fda40afd179a9564c24f7b9d9d

**Comment by bramley** [comment]
The licensing seems to have changed (July last year) and now redistribution is allowed

> As a software developer, use our DHTML scripts within a application/ program as part of its interface, such as a CSS menu being used as the program's navigation interface. The program itself can be distributable.
