### ISSUE TITLE
[BUG] PHP 8.0 error index php

### ISSUE THREAD

**Issue by rachid-a** [phpList/phplist3#809]
The index page gives the following error message with PHP 8.0.

 "PHP message: PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, string given in /var/www/localhost/phplist/phplist-3.6.5/public_html/lists/index.php:57
Stack trace:
#0 {main}
  thrown in /var/www/localhost/phplist/phplist-3.6.5/public_html/lists/index.php on line 57"

**Comment by michield** [comment]
what is your config value for ACCESS_CONTROL_ALLOW_ORIGINS ?

It needs to be an array for domains.

https://github.com/phpList/phplist3/blob/master/public_html/lists/index.php#L57

**Comment by michield** [comment]
Closing for lack of response

**Comment by leitmori** [comment]
I can confirm the behavior: Under PHP 7.4 for example `define('ACCESS_CONTROL_ALLOW_ORIGINS', ['https://example.com','https://example.org']);` can be used without problems, under PHP 8 you get a blank page.

**Comment by michield** [comment]
Ok, reopening for further review. PRs welcome

**Comment by michield** [comment]
That was resolved in [#842 ](https://github.com/phpList/phplist3/pull/842) and will make it to the next release
