### ISSUE TITLE
Possible XSS vulnerability

### ISSUE THREAD

**Issue by enferas** [phpList/phplist3#819]
Content removed (for now). Please use a[ responsible disclosure procedure](https://en.wikipedia.org/wiki/Responsible_disclosure) instead.

**Comment by michield** [comment]
I don't think that's a valid XSS issue, but if you can replicate it, let me know. The request param is sanitised with the vsprintf.

**Comment by michield** [comment]
I double checked and no, the parameter is santised even twice, so there's no XSS here.
