### ISSUE TITLE
Release 3.6.6-RC2 does not have the latest Trevelin theme

### ISSUE THREAD

**Issue by bramley** [phpList/phplist3#825]
In particular the last three PRs are not there, 120, 121 and [122](https://github.com/phpList/phplist-ui-bootlist/pull/122).

**Comment by michield** [comment]
That should work on the next run as well: https://github.com/phpList/phplist3/runs/4274334361?check_suite_focus=true#step:6:166

**Comment by michield** [comment]
@marianaballa it will be good to roll out another RC, just to double check
