### ISSUE TITLE
Session error, can"t login anymore

### ISSUE THREAD

**Issue by Singman33** [phpList/phplist3#826]
Hi,
I was using phpList 3.6.4 in September with no problem.
Today, I wanted to send a new campaign but each time I click on a button, I'm redirected to the login page to go further.
I've upgraded to 3.6.5 manually but now, I'm just unable to login.
After entering the login / password for admin, a quick red message appear about "session" then I go back to the login page.
I've activated the storage into the database to be sure it's not a problem about writting to a directory but still have the problem, sessions are ok.

- how can I see the error message ?
- do you know how to fix that ?

**Comment by marianaballa** [comment]
Hi @Singman33,

why don't you post your issue on the community forum so other members can see your question? The user forum is filled with experienced phpList users. 

https://discuss.phplist.org/

**Comment by michield** [comment]
This is better discussed on the forums

**Comment by Singman33** [comment]
Honestly, closing a ticket (even on Github) is not serious without asking the opener if he could follow the solution.
But I think you have stopped to be serious since a long time, otherwise you could see that **you have ZERO NEW SUBSCRIBERS** on the Discuss forum. Try to find why....

Hint : you never receive the email....

**Comment by michield** [comment]
Thanks for letting us know, we will look into that
