### ISSUE TITLE
Testing v3.6.6 RC3

### ISSUE THREAD

**Issue by marianaballa** [phpList/phplist3#827]
@bramley a new RC is available after the changes that @michield made. What are your thoughts about the RC? 

https://github.com/phpList/phplist3/releases/tag/v3.6.6-RC3
https://sourceforge.net/projects/phplist/files/phplist-development/3.6.6-RC3/

**Comment by bramley** [comment]
That looks a lot better! Thanks.

**Comment by michield** [comment]
Hmm, RC4 still pulls in the old UI, https://github.com/phpList/phplist3/runs/4325594201?check_suite_focus=true#step:9:168

I'll check why

**Comment by michield** [comment]
Ah, it's that annoying composer.lock file https://github.com/phpList/phplist3/blob/master/composer.lock#L1036

I keep forgetting that this doesn't pick it up automatically.

This commit fixes that: https://github.com/phpList/phplist3/commit/595fa770b61f7641432a462832ecc03f8a37b771
