### ISSUE TITLE
Change of styling on login page

### ISSUE THREAD

**Issue by bramley** [phpList/phplist3#828]
The login page has changed slightly in 3.6.6-RC3, some text is not being styled in the same way as previous release
In 3.6.5
![image](https://user-images.githubusercontent.com/3147688/142995119-fd0db6e0-a9e8-4e45-8e00-b6aca066bceb.png)
In 3.6.6.-RC3
![image](https://user-images.githubusercontent.com/3147688/142995178-57e5ec5c-3fdb-46b0-8628-5af6f3215bca.png)

The text was being given a class of "help-block" but is now being given "help-block/", so doesn't get styled correctly.

This seems to be caused by the upgrade to jquery and some badly-formatted literal html in some js files

    $('div.login p').contents().unwrap().wrap('<span id=helpBlock class=help-block/>');

It appears jquery now treats the trailing '/' as part of the class name, not as the closing tag. The html should have been well-formed to avoid this problem

    $('div.login p').contents().unwrap().wrap('<span id="helpBlock" class="help-block" />');

The .wrap() is used in three files but I am not sure which of these are actually used now
phpList3ToBootstrap.js
phplist_ui_bootlist.js
phplist_ui_bootlist.min.js

**Comment by michield** [comment]
That's probably here: https://github.com/phpList/phplist-ui-bootlist/blob/master/js/phpList3ToBootstrap.js#L167

the other ones are generated.

**Comment by michield** [comment]
Should be fixed in https://github.com/phpList/phplist-ui-bootlist/releases/tag/v2021-11-23

**Comment by bramley** [comment]
Looks good, thanks.
