### ISSUE TITLE
Attribute predefined values get a trailing newline

### ISSUE THREAD

**Issue by antzi** [phpList/phplist3#839]
When adding attribute predefined values as a list of entries, each on a new line, all values but the last get a newline character in the end. This breaks the subscriber export file format, campaign text using the attribute values and probably other things.

**Comment by michield** [comment]
Do you mean in this page? https://demo.phplist.org/lists/admin/?page=defaults

Does it happen for all of them, or did you check this on specific entries?

**Comment by antzi** [comment]
No, I mean this one - https://demo.phplist.org/lists/admin/?page=attributes
When I create a new attribute of type 'select', like that:

[image: Screenshot from 2021-12-15 01-09-10.png]

And click on 'Edit values' to add some options, like that:

[image: Screenshot from 2021-12-15 01-10-43.png]

When I later export the subscribers list in CSV and some of them have their
attribute set to one of the first 3 options, there is an additional newline
character at the end of the option text, i.e. Option 1 is in fact "Option
1\n". This breaks the CSV record. Only the last option of the list of
options added is not affected.

BR, Anastas

**Comment by bramley** [comment]
This is repeatable, the extra character is \r though.
When adding entries the POST data has \r\n line endings, but the code in editattributes.php splits the received string on \n only. Each entry added to the database has an extra \r character shown on the right-most column of this screenshot

![image](https://user-images.githubusercontent.com/3147688/146456389-af25a16c-2d47-44b5-8d0c-af41f4b0d122.png)

**Comment by antzi** [comment]
Thanks for the solution, patched it in my code. Hope it will go into the next release also.
