### ISSUE TITLE
Allow Installing Zipped Plugins from Other Sites than Github

### ISSUE THREAD

**Issue by mmx33** [phpList/phplist3#846]
Right now the web interface for installing plugins only allows plugins from Github. Could this limitation be removed? I personally do not want to host my plugins on Github, but I want to be able to install them over the web interface.

That's the part of the code I'm speaking of:

https://github.com/phpList/phplist3/blob/aa617dfbb9124581b49348dd69dbb171bfbc283f/public_html/lists/admin/plugins.php#L35-L41

I think removing the code would allow users to install plugins from Gitea or Gitlab instances.

**Comment by michield** [comment]
Yes, we can add other sources. Does Gitlab have a similar system that zips the code on the fly? If so, what is the URL pattern? Then we can add Gitlab as an additional approved source.

**Comment by bramley** [comment]
The code that checks for updates to plugins is specific to GitHub,  function getLatestTag().

**Comment by michield** [comment]
Thanks, we should keep that in mind. I'm all for adding Gitlab to the mix. In fact, I've often contemplated moving the official repo to Gitlab, but I guess that's a lot of work, so we can leave that for now. Gitlab is way better on Kudos on FOSS, certainly now that Github is in MS hands.

**Comment by michield** [comment]
Ok, so if a plugin lives on Gitlab eg https://gitlab.com/michield/phplist-plugin-smtpbalancer

The zip file URL is https://gitlab.com/michield/phplist-plugin-smtpbalancer/-/archive/master/phplist-plugin-smtpbalancer-master.zip

And you can fetch the tags from https://gitlab.com/api/v4/projects/michield%2Fphplist-plugin-smtpbalancer/repository/tags

So, that seems quite possible.

**Comment by bramley** [comment]
Fixed by #973
