### ISSUE TITLE
3.6.7 RC1 does not have the latest Updater or Common Plugin

### ISSUE THREAD

**Issue by bramley** [phpList/phplist3#851]
Updater is from last August, while Common plugin is from October. Both have been changed since then.

However the bootlist theme is the latest.

**Comment by michield** [comment]
So, can we work this out in a useful way. If you tag your plugins with versions, and we do the same with the updater, and then the composer file in phpList main uses "@stable" do you think that will work in an ongoing way?

**Comment by bramley** [comment]
The plugins are tagged already, e.g. https://github.com/bramley/phplist-plugin-common/releases/tag/3.18.0

But you can simply take the latest code on the "master" branch which should always be the latest tag. If it isn't then that's a mistake on my part.

You tagged the updater last week after one of my previous comments.

**Comment by michield** [comment]
Yes, I think the issue is that composer locks the versions. So, I should do an "composer update", but I don't want to do that on third party stuff.

https://github.com/phpList/phplist3/blob/master/composer.lock#L1080

I think we can do an "update" on specific packages only. I will add that to the CI

**Comment by michield** [comment]
Hmm, bit odd, the CI script does do a composer update.
I think it may have to be manual instead: https://github.com/phpList/phplist3/commit/8734df4896a8bf9425654cf4687282eef9da03eb

**Comment by michield** [comment]
@marianaballa this should be ok now
