### ISSUE TITLE
Extended permissions

### ISSUE THREAD

**Issue by sergioxdev** [phpList/phplist3#852]
Hi guys

congratulations for the excellent project, it works really well.

I had some questions:
- is it possible to allow an administrator (not superuser) to create a list and deny the config and system section?
- is it possible to allow 2 administrators (not superusers) to be able to modify the same users and the same lists?
- is it possible to add additional permissions for an administrator?

any suggestions or clarifications are accepted

**Comment by marianaballa** [comment]
Hi @sergioxdev! Thank you for your kind words!

These questions look like something the community would be able to answer. You can post the same message here: https://discuss.phplist.org/

The forum is filled with experienced phpList users.
