### ISSUE TITLE
Spaces removed from email content

### ISSUE THREAD

**Issue by djaho** [phpList/phplist3#863]
Hi,

I am using phpList to occasionally send a newsletter and have noticed that each time I do this, the content received when the campaign is sent is missing a few spaces. 
So for example, I write the following text:
"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc hendrerit lobortis porta. Pellentesque vestibulum nulla a varius vehicula."

And when the email is received, 1 or 2 whitespaces are missing, for example:
"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc hendreritlobortis porta. Pellentesque vestibulum nulla a varius vehicula."

This is of course example and not the actual text I sent.

I have tried sending the same content directly through PhpMailer over my SMTP provider and the issue didn't happen. 

From what I see, the issue happens when the content is moved in a new line in the original content of the email , for example:
_Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc hendreritl=
obortis porta. Pellentesque vestibulum nulla a varius vehicula._

When the line break happens, a space is removed. 

Does anyone by any chance has an idea on how to resolve this issue?
One way to bypass it is to change all these spaces with &nbsp; but this of course isn't a perfect solution.

Can anyone share where in the phplist could we control the length of the line in the original content? I can't seem to understand why phplist puts extra content in a new line.

Thank you

**Comment by djaho** [comment]
A bit more info. The issue seems to be very similar to the one described here: https://github.com/swiftmailer/swiftmailer/issues/601

**Comment by djaho** [comment]
It turned out that setting the word wrap for HTML to 75 characters resolved the issue for HTML content (although not for text content, but I mostly care about HTML).

Here is how to set this up:
define('WORDWRAP_HTML', 75);

Would still love if anyone can chime in and give us a bit of an insight as to why this could be happening.
It could be that without this setting, phpmailer wrapped the content for a specific width and then the SMTP server re-wrapped it and some whitespaces got lots in the process.

**Comment by michield** [comment]
Yes. the wordwrap will help here. You can also place around with the HTML encoding setting:

https://resources.phplist.com/system/config/htmlemail_encoding

**Comment by michield** [comment]
If you find there's a need to update the code, you can open a Pull Request
