### ISSUE TITLE
Very slow admin pages because of checkForUpdate()

### ISSUE THREAD

**Issue by mathieumd** [phpList/phplist3#870]
Our private phpList server has no web connection. This makes the `checkForUpdate()` to awfully slow down every admin pages!

Removing `$updateNotif = checkForUpdate();` from [admin/index.php L531](https://github.com/phpList/phplist3/blob/master/public_html/lists/admin/index.php#L531) does solve the problem, but I think it should be configurable.

You may also want to comment/remove the bloc [L539-L541](https://github.com/phpList/phplist3/blob/master/public_html/lists/admin/index.php#L539-L541) to get rid of the "Download new version" message box.

**Comment by bramley** [comment]
You can disable that check by adding/changing this setting in config.php to disable the updater

    define('ALLOW_UPDATER', false);

The content of the community news section is usually cached but if the attempt to fetch the url fails then that might be repeated on each load of only the home page.

**Comment by mathieumd** [comment]
Thanks @bramley! This constant was evaluated a few lines above, I don't know how I could not see it!!

However, it might be nice to also have a similar setting to disable all Internet requests (like news feed, or anything).

**Comment by michield** [comment]
You may want to consider whitelisting a few URLs/domains. phpList will also check for new translations, top level domains, and without egress, you won' t be able to use send-a-webpage. But I guess those are only on request, and not on every page load. 

It will check the community newsfeed once a day: https://github.com/phpList/phplist3/blob/master/public_html/lists/admin/index.php#L647

If you want, you can send a PR to add a flag. Most requests will go through fetchURL: https://github.com/phpList/phplist3/blob/master/public_html/lists/admin/lib.php#L1233
