### ISSUE TITLE
Default FROM address is not considered

### ISSUE THREAD

**Issue by tobelix87** [phpList/phplist3#871]
I set via admin panel the default sender address of a campaign. This is also shown in database table _config_ in field _campaignfrom_default_. For me it is working fine. When I create a new campaign, the default email address is shown in the _From Line_ field.
But I have a second admin account. For this user it always takes the email address which is linked with the admin account. Why is the default address not taken?

**Comment by michield** [comment]
You can define that behaviour with USE_ADMIN_DETAILS_FOR_MESSAGES

https://github.com/phpList/phplist3/blob/master/public_html/lists/admin/send_core.php#L660

https://resources.phplist.com/system/config/use_admin_details_for_messages

Basically, when you have multiple administrators, phpList assumes that everyone will want to send as them, and not as the centrally defined FROM. But you can switch that off if you want it working differently.

**Comment by tobelix87** [comment]
that worked. didnt see that config parameter.
Many thanks!
