### ISSUE TITLE
PHP Fatal error in embedremoteimages plugin

### ISSUE THREAD

**Issue by jr-clark** [phpList/phplist3#880]
When the embedremoteimages plugin is enabled (Config -> Manage Plugins) and selected (Format -> Send as -> HTML, with remote images embedded ) the system generates :

"PHP message: PHP Fatal error:  Uncaught Error: Cannot access private property phplistMailer::$image_types in /var/www/vhosts/.../admin/plugins/embedremoteimages.php:34"

image_types was changed to private in class.phplistmailer.php in 3.4.8

**Comment by michield** [comment]
That is better reported in the plugin itself https://github.com/michield/phplist-plugin-embedremoteimages/issues
