### ISSUE TITLE
Changes to the method of sending emails in config.php

### ISSUE THREAD

**Issue by bramley** [phpList/phplist3#883]
This commit from last year https://github.com/phpList/phplist3/commit/fef5e45d64daf011f7d9259f2c6c81c347312f71 has a change to the config.php file that seems to make phplist not work "out of the box". 

Previously the default was to send emails through the php mail() function because PHPMAILERHOST was set to an empty string. The setting for PHPMAILERHOST is now "localhost" with PHPMAILERPORT of 2500 which are unlikely to work for any hosted servers. I guess that they are valid for docker.
At least the preceding comment needs to be changed because the usual case will be that PHPMAILERHOST does need to be changed to either an SMTP server or an empty string.

```
// if you have an SMTP server, set it here. Otherwise it will use the normal php mail() function
//# if your SMTP server is called "smtp.mydomain.com" you enter this below like this:
//#
//#     define("PHPMAILERHOST",'smtp.mydomain.com');

```
Another change was setting TEST to 0 instead of 1 which kind of makes the setting redundant. Again, at least the preceding comment needs to be updated.

**Comment by michield** [comment]
Yes, good point. I will revert a few of those changes. They shouldn' t have gone out.

**Comment by michield** [comment]
Updated in #886
