### ISSUE TITLE
Rendering of pages on resources.phplist.com

### ISSUE THREAD

**Issue by bramley** [phpList/phplist3#889]
I have noticed a change in how some pages are formatted.  A single underscore seems to be treated as starting italic, in addition to the usual `//`. This messes up pages that refer to variable names or constants e.g `PLUGIN_ROOTDIR`

As an example https://resources.phplist.com/develop/plugins#multiple_plugin_locations

From what I can see that is markdown formatting. Is there a dokuwiki markdown plugin that has inadvertently been enabled?

**Comment by michield** [comment]
Yes, that's weird, we should look into that.

**Comment by michield** [comment]
I disabled the markdown plugin, but that didn't resolve it.

Tbh, the whole resources wiki can do with a revamp. I will try to find some time for that.

**Comment by bramley** [comment]
This appears to have been fixed by the recent upgrade to dokuwiki.
