### ISSUE TITLE
Typo of PHP_EOL

### ISSUE THREAD

**Issue by bramley** [phpList/phplist3#893]
In 3.6.9-RC2 there is a mistype of PHP_EOL in connect.php

https://github.com/phpList/phplist3/pull/886/files#diff-a58d59211ff2a40cdba18a95fa1fc84cf882767d95735f18762085ef7f02823f

**Comment by michield** [comment]
Fixed in 8b1a432a7b8da75ffad78e8211f7ccf1835c1aaa
