### ISSUE TITLE
Plugins not latest version

### ISSUE THREAD

**Issue by bramley** [phpList/phplist3#894]
Release 3.6.9-RC2 needs to include the latest versions of the Captcha and Common plugins.

**Comment by michield** [comment]
yes, that's because the reference is stuck in composer.lock. It needs manually updating.

Would it be an option if you create a PR when the plugins need changing?

**Comment by bramley** [comment]
I'm not sure that I understand the steps of the release process but simply updating composer will bring in the latest plugins. 

`composer update`

Then the post-update script copies the plugin files to the right place.

There are a couple of warnings both of which can be ignored.

**Comment by michield** [comment]
The release just uses the composer.lock

https://github.com/phpList/phplist3/blob/master/.github/workflows/build-release.yml#L44

So, we need to push a new lock file manually to tell it to use the new versions.

I'll do that and also fix that PHP_EOL typo

**Comment by michield** [comment]
merged into release branch
