### ISSUE TITLE
please document copyright/license

### ISSUE THREAD

**Issue by onlyjob** [phpList/phplist3#9]
Please document origin, copyright and license for images in 
- `public_html/lists/images/smiley`
- `public_html/lists/admin/ui/dressprow/images/*x*`

It is unlikely that those icon set and smiles are under AGPL-3...

**Comment by michield** [comment]
smileys removed, as they are not in use. They did originate from the fckeditor (iirc)

**Comment by michield** [comment]
dressprow is remote repo, with it's own license. Images referred here https://github.com/phpList/phplist-ui-dressprow/blob/master/images/icons.txt

**Comment by onlyjob** [comment]
And links in this file are dead? I can't find any licensing information by following those links.

**Comment by michield** [comment]
I will ask the persons who added the icons. I think they were public domain, but not sure.

**Comment by onlyjob** [comment]
Thanks.

**Comment by tarekdj** [comment]
Hi all,
@onlyjob you are right liks are dead. Icons were under CC license. 
I found a copy of the archive here https://github.com/nick-desteffen/dev_icons/blob/master/pc.de-duesseldorf-icon-pack.zip. It seem like they renamed it from Munich to duesseldorf.

**Comment by michield** [comment]
Or it's this one: https://github.com/nick-desteffen/dev_icons/blob/master/pc.de-munich-icon-pack.zip

**Comment by tarekdj** [comment]
@michield munich icons are orange. We are using the dark one (those on duesseldorf zip )
