### ISSUE TITLE
How to translate the buttons on the subscription page

### ISSUE THREAD

**Issue by baiyanghk** [phpList/phplist3#904]
The translation of my subscription page button did not work, how do I translate it correctly in the following file

I need to translate this word：Subscribe

My Demo Station：http://phplist.likesyou.org/?p=subscribe

1.public_html\lists\admin\locale\zh_CN\phplist.po

2.public_html\lists\admin\locale\zh_CN\pagetitles.php

3.public_html\lists\admin\defaultFrontendTexts.php

**Comment by marianaballa** [comment]
You can translate phpList here: https://translate.phplist.org/ 

Note that, the new translations will be merged when a new version is ready to be released.

**Comment by baiyanghk** [comment]
> 



> You can translate phpList here: https://translate.phplist.org/
> 
> Note that, the new translations will be merged when a new version is ready to be released.

This translation site is closed for registration and does not work, and there is no search for the location of the term.

**Comment by michield** [comment]
You can change the text on that button in phpList itself. When you create a subscribe page, there' s a box to change what the button says

![image](https://user-images.githubusercontent.com/569843/198850075-3da6f53e-5c65-46d0-bc45-c83cedb7fffe.png)

Also "Frontend" translations are managed here: https://github.com/phpList/phplist-lan-texts

You can create a PR to make changes.

More info can be found here: https://resources.phplist.com/translations/start

https://translate.phplist.org/ is to translate the backend application. @marianaballa can create you an account.

**Comment by baiyanghk** [comment]
@marianaballa   Please help me to open a translation account, I want to do Chinese language maintenance, my email is：dayadiguo@gmail.com

**Comment by marianaballa** [comment]
@baiyanghk I have created an account with your email. By right, you should have received an invitation via email. 

I have given you access to the following languages, as I was unsure which one you would be interested in translating. 

![image](https://user-images.githubusercontent.com/23120908/198901291-1a485dcc-dca1-43af-9f1f-90e33e1f1433.png)

Let me know if you are able to login to your account and translate.

**Comment by baiyanghk** [comment]
@marianaballa  I don't receive emails, is it that gmail can't receive them?

**Comment by marianaballa** [comment]
You are right. I tested it and it seems the system has not sent out any emails. 

Please give me some time to investigate a bit further what the issue might be.

**Comment by marianaballa** [comment]
@baiyanghk I have manually created an account for you and emailed the credentials.

**Comment by baiyanghk** [comment]
> 

Thank you, I have been able to log into my account for operation, thank you very much!

**Comment by marianaballa** [comment]
I am glad to hear that! Thank you for your contributions to phpList :)
