### ISSUE TITLE
division by zero in statsoverview.php on line 148

### ISSUE THREAD

**Issue by muelli** [phpList/phplist3#910]
https://github.com/phpList/phplist3/blob/0a6b74b1f49b83d67bba419b1e2ffe5109f7faf3/public_html/lists/admin/statsoverview.php#L148

```$perc = sprintf('%0.2f', $viewed[0] / ($totalSent - $totalBounced) * 100);```

this seems to be able to produce an exception :(

**Comment by muelli** [comment]
https://github.com/phpList/phplist3/blob/0a6b74b1f49b83d67bba419b1e2ffe5109f7faf3/public_html/lists/admin/statsoverview.php#L159

https://github.com/phpList/phplist3/blob/0a6b74b1f49b83d67bba419b1e2ffe5109f7faf3/public_html/lists/admin/statsoverview.php#L167


here, too

**Comment by michield** [comment]
Yes, I guess if all sent emails bounced, then it's a division by zero

**Comment by muelli** [comment]
yeah. or if nothing has been sent yet (for whatever reason).

It's been a bit annoying to track down this problem, because `error_reporting` is set to 0. And also the `@include` hides failures like this.

**Comment by michield** [comment]
Yeah, in production, I rather have a blank page than show a stack trace, for security reasons.

As a dev, you can set "developer_email" and "show_dev_errors" in your config file to debug these kinds of issues.

https://github.com/phpList/phplist3/blob/main/public_html/lists/admin/init.php#L37

**Comment by michield** [comment]
#913 should fix that
