### ISSUE TITLE
Include Updater plugin in 3.6.13

### ISSUE THREAD

**Issue by bramley** [phpList/phplist3#957]
@marianaphplist 
The 3.6.13-RC1 release includes the Addons plugin, not the Updater plugin. Can a new RC be made including that plugin? I noticed that composer.json had been changed on the 3.6.13 branch but did not realise that was after the RC1 release.

**Comment by michield** [comment]
Yes, I made the changes without a PR straight to the release branch. I think it'll work, but we will need to roll out a new RC to be sure.

**Comment by michield** [comment]
This should now be in 3.6.13-RC2

I tested it by changing the line in init.php to define 3.6.11 in the docker version. 

it upgraded to 3.6.12 without any issues.

**Comment by bramley** [comment]
Thanks.
