### ISSUE TITLE
3.6.13-rc1 - Undefined function in processing bounces

### ISSUE THREAD

**Issue by enricozamprogno** [phpList/phplist3#958]
I forgot to enable pop3 protocol on our firewall and phplist gave me this error

( ! ) Error: Call to undefined function output() in /var/www/html/bollettino/lists/admin/lib.php on line 962
Call Stack
#	Time	Memory	Function	Location
1	0.0001	394128	{main}( )	.../index.php:0
2	0.0158	949696	include( '/var/www/html/bollettino/lists/admin/processbounces.php )	.../index.php:759
3	0.0158	933424	getPageLock( $force = ??? )	.../processbounces.php:488

the page URL is /lists/admin/?page=processbounces 

inserting in lib.php the declaration of the output function taken from another module everything seems to work

**Comment by enricozamprogno** [comment]
Proposed patch #959

**Comment by michield** [comment]
Fixed with #959
