### ISSUE TITLE
Feature request: ability to bulk remove subscribers from list with copy + paste

### ISSUE THREAD

**Issue by doug86i** [phpList/phplist3#964]
The copy and paste box is a great way to add existing subscribers to a new list.

We would love to be able to paste in a list of email addresses to **_remove_** them from a list in the same way.

For instance to avoid advertising to subscribers that have already purchased a particular product.

All the best,

Dx

**Comment by michield** [comment]
What you can do in that situation is the following:

- create a list called "Clients who purchased product X"
- enable the "list exclude" feature https://resources.phplist.com/system/config/use_list_exclude
- when sending, send it to your normal lists, but on the "exclude" tab, tick the box "clients who purchased X"
- phpList will avoid sending to the subscribers who already purchased.

**Comment by doug86i** [comment]
Thanks @michield that's very helpful!

It does solve our immediate issue but I do also think the ability to bulk remove users would be a worthwhile addition.

Thanks for your help x

**Comment by bramley** [comment]
@doug86i You can use the Subscribers plugin to do this. See https://resources.phplist.com/plugin/subscribers#subscriber_commands

**Comment by doug86i** [comment]
@bramley This is perfect! Thanks so much x
