### ISSUE TITLE
Privacy Issue: Unsubscribing response messages

### ISSUE THREAD

**Issue by kleozzy** [phpList/phplist3#967]
Hello ,

Testing on latest build: 3.6.13 i see that there are different messages when unsubscribing: 
1. For a valid subbed email and 
2. For a non-subbed email.

The distinct messages can be used by someone to identify subbed emails based on the response messages. Is there a way to adjust this so that the message is always the same (generic), regardless of validity ?

Is it something that can be added into the templates so that we can easily change without messing with the code itself ?

**Comment by michield** [comment]
I can't recall that. Can you give screenshots of the two situations? It can probably be managed with a language string.

**Comment by kleozzy** [comment]
Sure here they are:

1. Non-valid email
![image](https://github.com/phpList/phplist3/assets/29057778/036b675d-83fb-4048-b052-c54f26db4a35)
2. Valid email
![image](https://github.com/phpList/phplist3/assets/29057778/93bc2bff-a01a-45c0-a6bd-c2d3d92cffc8)

**Comment by michield** [comment]
Thanks. You can change that by changing this string https://github.com/phpList/phplist-lan-texts/blob/master/english.inc#L44

to be the same one as the valid email one.

**Comment by michield** [comment]
I guess it will make sense to change both to something like "if you were subscribed, you will receive a confirmation of unsubscription shortly" or something like that.

**Comment by kleozzy** [comment]
Exactly

**Comment by michield** [comment]
Resolved with https://github.com/phpList/phplist-lan-texts/commit/3933161d06a86c1d5018daeae07c5ddff5a7a3f6
