### ISSUE TITLE
e-mail address username-@example.com marked as invalid

### ISSUE THREAD

**Issue by pve-paymorrow** [phpList/phplist3#984]
Hi, team,
in our database we have few e-mail addresses containing hyphen just before @. Those addresses are valid (we sent e-mail to those addresses and got response), but phplist marked them as invalid. I'm not sure which RFC defines e-mail address format; according to https://en.wikipedia.org/wiki/Email_address#Valid_email_addresses Wikipedia article:
_**Valid email addresses**
user-@example.org (local-part ending with non-alphanumeric character from the list of allowed printable characters)_
the address is valid
Please consider to not to mark this address format as invalid. Thank you

**Comment by michield** [comment]
The "official" email format allows all kinds of crazy email addresses, even ones that have the user part on multiple lines. Most systems around the internet have opted for a more simple approach, including phpList.

If you want, you can remove this line to see if it passes:

https://github.com/phpList/phplist3/blob/main/public_html/lists/admin/inc/userlib.php#L727

**Comment by pve-paymorrow** [comment]
OK, thank your for explanation the reasons why it's considered invalid and for help where in the source the checking code is.
