### ISSUE TITLE
Resend mail to recipients that were blocked accidently

### ISSUE THREAD

**Issue by blu-IT** [phpList/phplist3#985]
Hi,

I have some recipients that did not recieve a newsletter. They all have a gmail-address. Gmail did not like the fact that SPF wasn't already configured (in the past there were no problems). So I have a bunch of recipients that did not recieve the last newsletter and were blocked with error code **550-5.7.26**: 

```
host gmail-smtp-in.l.google.com [108.177.15.26]
SMTP error from remote mail server after end of data:
550-5.7.26 This mail is unauthenticated, which poses a security risk to the
550-5.7.26 sender and Gmail users, and has been blocked. The sender must
550-5.7.26 authenticate with at least one of SPF or DKIM. For this message,
550-5.7.26 DKIM checks did not pass and SPF check for [mydomain.com] did not
550-5.7.26 pass with ip: [80.67.18.29]. The sender should visit
550-5.7.26 https://support.google.com/mail/answer/81126#authentication for
550 5.7.26 instructions on setting up authentication. bg32-20020a05600c3ca000b003fbc722b14asi5474471wmb.135 - gsmtp
```

Is there a way to resend the last mail **only to this blocked users** or to create a rule, that resends the mail to users in "msgbounces"?

Thanks!

**Comment by bramley** [comment]
You can use the Campaigns plugin to resend a campaign. See the plugin's documentation page https://resources.phplist.com/plugin/campaigns

**Comment by blu-IT** [comment]
@bramley 

Hi,

unfortunately I can not find the function "Resend campaign" as mentioned in the documentation screenshots.
The plugin is installed and activated.

In the campaigns overview I have only the options "resend to subscribers" or "requeue". Can you point me to the right menue please?

Thanks!

**Comment by blu-IT** [comment]
OK, I was to afraid of clicking something wrong. Solution 1 is what I was looking for.

Thanks!

**Comment by blu-IT** [comment]
Somekind of strange... now the buttons showed in the screenshot above dissapeard. They aren`t available anymore with any old message.

**Comment by blu-IT** [comment]
Sorry, can be closed!
