### ISSUE TITLE
User IDs get used up - int(11) limit reached

### ISSUE THREAD

**Issue by itofficeeu** [phpList/phplist3#991]
Hi, we have the case where the IDs of the user table reaches its limit. The field has the type int(11).

Does there exists a tool to compact the IDs.

We have only 300.000 users. But somehow are users registering and then deleting themselves and their data again. I guess bots or hackers. The result is big gaps of 100.000 or more not used IDs between users staying for long time.

We know how to fix this manually, but maybe there already is a tool for the situation.

PhpList v. 3.6.8 - 3.6.13

Thanks

**Comment by michield** [comment]
I don't know of any tool, but you can probably just convert the ID column to a BIGINT, that should keep you going for a while.

**Comment by itofficeeu** [comment]
Thanks, that is what we did for now.
