### ISSUE TITLE
Mailgun API 

### ISSUE THREAD

**Issue by dlpCttl** [phpList/phplist3#998]
Yo,

I got this error when i try to send an email (test).

Fatal error: Uncaught Http\Discovery\Exception\DiscoveryFailedException: Could not find resource using any discovery strategy. Find more information at http://docs.php-http.org/en/latest/discovery.html#common-errors - No valid candidate found using strategy "Http\Discovery\Strategy\CommonClassesStrategy". We tested the following candidates: . - No valid candidate found using strategy "Http\Discovery\Strategy\CommonPsr17ClassesStrategy". We tested the following candidates: Phalcon\Http\Message\UriFactory, Nyholm\Psr7\Factory\Psr17Factory, Zend\Diactoros\UriFactory, GuzzleHttp\Psr7\HttpFactory, Http\Factory\Diactoros\UriFactory, Http\Factory\Guzzle\UriFactory, Http\Factory\Slim\UriFactory, Laminas\Diactoros\UriFactory, Slim\Psr7\Factory\UriFactory. in /htdocs/lists/admin/plugins/Mailgun/vendor/php-http/discovery/src/Exception/DiscoveryFailedException.php:41 Stack trace: #0 /htdocs/lists/admin/plugins/Mailgun/vendor/php-http/discovery/src/ClassDiscovery.php(85): Http\Discovery\Exception\DiscoveryFailedException::create(Array) #1 /htdocs/lists/admin/plugins/Mailgun/vendor/php-http/discovery/src/Psr17FactoryDiscovery.php(117): Http\Discovery\ClassDiscovery::findOneByType('Psr\\Http\\Messag...') #2 /htdocs/lists/admin/plugins/Mailgun/vendor/php-http/discovery/src/Psr17FactoryDiscovery.php(134): Http\Discovery\Psr17FactoryDiscovery::findUriFactory() #3 /htdocs/lists/admin/plugins/Mailgun/vendor/mailgun/mailgun-php/src/HttpClient/HttpClientConfigurator.php(114): Http\Discovery\Psr17FactoryDiscovery::findUrlFactory() #4 /htdocs/lists/admin/plugins/Mailgun/vendor/mailgun/mailgun-php/src/HttpClient/HttpClientConfigurator.php(70): Mailgun\HttpClient\HttpClientConfigurator->getUriFactory() #5 /htdocs/lists/admin/plugins/Mailgun/vendor/mailgun/mailgun-php/src/Mailgun.php(83): Mailgun\HttpClient\HttpClientConfigurator->createConfiguredClient() #6 /htdocs/lists/admin/plugins/Mailgun/vendor/mailgun/mailgun-php/src/Mailgun.php(99): Mailgun\Mailgun->__construct(Object(Mailgun\HttpClient\HttpClientConfigurator)) #7 /htdocs/lists/admin/plugins/Mailgun.php(124): Mailgun\Mailgun::create('562708e6bcdd03d...', 'https://api.eu....') #8 /htdocs/lists/admin/class.phplistmailer.php(731): Mailgun->send(Object(phplistMailer), 'Received: from ...', 'This is a multi...') #9 /htdocs/lists/admin/PHPMailer6/src/PHPMailer.php(1668): phplistMailer->pluginSend('Received: from ...', 'This is a multi...') #10 /htdocs/lists/admin/PHPMailer6/src/PHPMailer.php(1500): PHPMailer\PHPMailer\PHPMailer->postSend() #11 /htdocs/lists/admin/class.phplistmailer.php(299): PHPMailer\PHPMailer\PHPMailer->send() #12 /htdocs/lists/admin/sendemaillib.php(917): phplistMailer->compatSend() #13 /htdocs/lists/admin/send_core.php(496): sendEmail() #14 /htdocs/lists/admin/send.php(124): include('/htdocs/lists/a...') #15 /htdocs/lists/admin/index.php(752): include('/htdocs/lists/a...') #16 {main} Next Http\Discovery\Exception\NotFoundException: No PSR-17 url factory found. Install a package from this list: https://packagist.org/providers/psr/http-factory-implementation in /htdocs/lists/admin/plugins/Mailgun/vendor/php-http/discovery/src/Psr17FactoryDiscovery.php:22 Stack trace: #0 /htdocs/lists/admin/plugins/Mailgun/vendor/php-http/discovery/src/Psr17FactoryDiscovery.php(119): Http\Discovery\Psr17FactoryDiscovery::createException('url factory', Object(Http\Discovery\Exception\DiscoveryFailedException)) #1 /htdocs/lists/admin/plugins/Mailgun/vendor/php-http/discovery/src/Psr17FactoryDiscovery.php(134): Http\Discovery\Psr17FactoryDiscovery::findUriFactory() #2 /htdocs/lists/admin/plugins/Mailgun/vendor/mailgun/mailgun-php/src/HttpClient/HttpClientConfigurator.php(114): Http\Discovery\Psr17FactoryDiscovery::findUrlFactory() #3 /htdocs/lists/admin/plugins/Mailgun/vendor/mailgun/mailgun-php/src/HttpClient/HttpClientConfigurator.php(70): Mailgun\HttpClient\HttpClientConfigurator->getUriFactory() #4 /htdocs/lists/admin/plugins/Mailgun/vendor/mailgun/mailgun-php/src/Mailgun.php(83): Mailgun\HttpClient\HttpClientConfigurator->createConfiguredClient() #5 /htdocs/lists/admin/plugins/Mailgun/vendor/mailgun/mailgun-php/src/Mailgun.php(99): Mailgun\Mailgun->__construct(Object(Mailgun\HttpClient\HttpClientConfigurator)) #6 /htdocs/lists/admin/plugins/Mailgun.php(124): Mailgun\Mailgun::create('562708e6bcdd03d...', 'https://api.eu....') #7 /htdocs/lists/admin/class.phplistmailer.php(731): Mailgun->send(Object(phplistMailer), 'Received: from ...', 'This is a multi...') #8 /htdocs/lists/admin/PHPMailer6/src/PHPMailer.php(1668): phplistMailer->pluginSend('Received: from ...', 'This is a multi...') #9 /htdocs/lists/admin/PHPMailer6/src/PHPMailer.php(1500): PHPMailer\PHPMailer\PHPMailer->postSend() #10 /htdocs/lists/admin/class.phplistmailer.php(299): PHPMailer\PHPMailer\PHPMailer->send() #11 /htdocs/lists/admin/sendemaillib.php(917): phplistMailer->compatSend() #12 /htdocs/lists/admin/send_core.php(496): sendEmail() #13 /htdocs/lists/admin/send.php(124): include('/htdocs/lists/a...') #14 /htdocs/lists/admin/index.php(752): include('/htdocs/lists/a...') #15 {main} thrown in /htdocs/lists/admin/plugins/Mailgun/vendor/php-http/discovery/src/Psr17FactoryDiscovery.php on line 22

Help please ^^

**Comment by bramley** [comment]
I cannot repeat this problem. How did you install phplist and the Mailgun plugin?

**Comment by bramley** [comment]
@dlpCttl I think some of the packages need updating. But this works for me because I have other plugins installed that coincidentally provide the right version of packages.

**Comment by dlpCttl** [comment]
@bramley Thanks a lot, it's working..

I have another problem now : 

Débuté
Le processus a démarré,
Une campagne à traiter.
Veuillez garder cette fenêtre ouverte. phpList va traiter la file d'attente jusqu'à ce que l'ensemble des messages ait été envoyé. Ceci peut prendre du temps
Le rapport d'exécution sera envoyé par courriel
Message de traitement 10
Recherche d'abonnés
Trouvés: 167 à traiter
**Error: Process Killed by other process**

Envoi en lots de 1,000 messages
Script stage: 5
101 messages sent in 41,39 seconds (8785 msgs/hr)
Finished this run
Less than batch size were sent, so reloading imminently

Any idea ?
